formats["am-et"] = [
  'dddd, d MMMM yyyy h:mm:ss a',
  'dddd, d MMMM yyyy HH:mm:ss',
  'd MMMM yyyy h:mm:ss a',
  'd MMM yyyy h:mm:ss a',
  'd MMMM yyyy HH:mm:ss',
  'dd/MM/yyyy h:mm:ss a',
  'd MMM yyyy HH:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'dddd, d MMMM yyyy',
  'EEEE, d MMMM y',
  'h:mm:ss a zzzz',
  'd MMMM yyyy',
  'h:mm:ss a z',
  'd MMM yyyy',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'MMMM dd',
  'd MMM y',
  'dd/MM/y',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];