formats["as-in"] = [
  'dd-MM-yyyy a hh:mm:ss',
  'dd-MM-yyyy a h:mm:ss',
  'dd-MM-yyyy H:mm:ss',
  'EEEE, d MMMM, y',
  'h.mm.ss a zzzz',
  'h.mm.ss a z',
  'a hh:mm:ss',
  'dd-MM-yyyy',
  'MMMM,yyyy',
  'a h:mm:ss',
  'd MMMM, y',
  'h.mm.ss a',
  'H:mm:ss',
  'MMMM dd',
  'MMMM,yy',
  'dd-MM-y',
  'h.mm. a',
  'd-M-y',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy,MMMM dd, EEEE a hh:mm:ss',
  'yyyy,MMMM dd, EEEE a h:mm:ss',
  'yyyy,MMMM dd, EEEE H:mm:ss',
  'yyyy,MMMM dd, EEEE'
];