formats["az-latn-az"] = [
  'dd MMMM yyyy HH:mm:ss',
  'd MMMM yyyy HH:mm:ss',
  'dd MMMM yyyy H:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'dd MMMM yyyy HH:mm',
  'dd.MM.yyyy H:mm:ss',
  'd MMMM yyyy HH:mm',
  'dd MMMM yyyy H:mm',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'd MMMM yyyy H:mm',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd/MM/yy H:mm:ss',
  'd.M.yy HH:mm:ss',
  'dd.MM.yyyy H:mm',
  'd MMMM y, EEEE',
  'd.M.yy H:mm:ss',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'HH:mm:ss zzzz',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'd.M.yy HH:mm',
  'dd MMMM yyyy',
  'd MMMM yyyy',
  'd.M.yy H:mm',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'd MMMM',
  'd.M.yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];