formats["be-by"] = [
  'd MMMM yyyy HH:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'd MMMM yyyy HH:mm',
  'dd.MM.yy HH:mm:ss',
  'd MMMM yyyy H:mm',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd.MM.yyyy H:mm',
  'EEEE, d MMMM y',
  'dd.MM.yy HH:mm',
  'HH.mm.ss zzzz',
  'dd.MM.yy H:mm',
  'd MMMM yyyy',
  'HH.mm.ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'HH.mm.ss',
  'HH:mm:ss',
  'd MMMM y',
  'dd.MM.yy',
  'H:mm:ss',
  'd MMMM',
  'd.M.yy',
  'HH.mm',
  'HH:mm',
  'd.M.y',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];