formats["bg-bg"] = [
  'EEEE, dd MMMM yyyy \'г.\' HH:mm:ss',
  'EEEE, dd MMMM yyyy \'г.\' H:mm:ss',
  'EEEE, dd MMMM yyyy \'г.\' HH:mm',
  'EEEE, dd MMMM yyyy \'г.\' H:mm',
  'dd MMMM yyyy \'г.\' HH:mm:ss',
  'dd MMMM yyyy \'г.\' H:mm:ss',
  'dd.MM.yyyy \'г.\' HH:mm:ss',
  'EEEE, dd MMMM yyyy \'г.\'',
  'dd MMMM yyyy \'г.\' HH:mm',
  'dd.M.yyyy \'г.\' HH:mm:ss',
  'dd.MM.yyyy \'г.\' H:mm:ss',
  'd.M.yyyy \'г.\' HH:mm:ss',
  'dd MMMM yyyy \'г.\' H:mm',
  'dd.M.yyyy \'г.\' H:mm:ss',
  'd.M.yyyy \'г.\' H:mm:ss',
  'dd.MM.yyyy \'г.\' HH:mm',
  'EEEE, d MMMM y \'г\'.',
  'dd.M.yyyy \'г.\' HH:mm',
  'dd.MM.yyyy \'г.\' H:mm',
  'd.M.yyyy \'г.\' HH:mm',
  'dd.M.yyyy \'г.\' H:mm',
  'd.M.yyyy \'г.\' H:mm',
  'dd MMMM yyyy \'г.\'',
  'dd.MM.yyyy \'г.\'',
  'MMMM yyyy \'г.\'',
  'd MMMM y \'г\'.',
  'dd.M.yyyy \'г.\'',
  'd.M.yyyy \'г.\'',
  'd.MM.yy \'г\'.',
  'd.MM.y \'г\'.',
  'H:mm:ss zzzz',
  'H:mm:ss z',
  'HH:mm:ss',
  'H:mm:ss',
  'dd MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];