formats["bn-in"] = [
  'dd MMMM yyyy a hh.mm.ss',
  'd MMMM yyyy a hh.mm.ss',
  'dd MMMM yyyy a h.mm.ss',
  'd MMMM yyyy a h.mm.ss',
  'dd MMMM yyyy HH.mm.ss',
  'dd-MM-yyyy a hh.mm.ss',
  'd MMMM yyyy HH.mm.ss',
  'dd MMMM yyyy H.mm.ss',
  'dd-MM-yyyy a h.mm.ss',
  'd MMMM yyyy H.mm.ss',
  'dd-MM-yy a hh.mm.ss',
  'dd-MM-yyyy HH.mm.ss',
  'dd-MM-yy a h.mm.ss',
  'dd-MM-yyyy H.mm.ss',
  'd-M-yy a hh.mm.ss',
  'dd-MM-yy HH.mm.ss',
  'd-M-yy a h.mm.ss',
  'dd-MM-yy H.mm.ss',
  'EEEE, d MMMM, y',
  'd-M-yy HH.mm.ss',
  'd-M-yy H.mm.ss',
  'h:mm:ss a zzzz',
  'dd MMMM yyyy',
  'd MMMM yyyy',
  'h:mm:ss a z',
  'MMMM, yyyy',
  'a hh.mm.ss',
  'dd-MM-yyyy',
  'a h.mm.ss',
  'd MMMM, y',
  'h:mm:ss a',
  'HH.mm.ss',
  'd MMM, y',
  'dd-MM-yy',
  'H.mm.ss',
  'MMMM dd',
  'd-M-yy',
  'd/M/yy',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];