formats["bo-cn"] = [
  'EEEE d MMMM y',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'HH:mm:ss',
  'd MMMM y',
  'MMMM dd',
  'd MMM y',
  'HH:mm',
  'yyyy\'ལོའི་ཟླ\' M\'ཚེས\' d EEEE HH:mm:ss',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy\'ལོའི་ཟླ\' M\'ཚེས\' d HH:mm:ss',
  'yyyy\'ལོའི་ཟླ\' M\'ཚེས\' d EEEE',
  'yyyyལོའི་ཟླ MMM d EEEE HH:mm:ss',
  'yyyy\'ལོའི་ཟླ\' M\'ཚེས\' d',
  'yyyyལོའི་ཟླ MMM d HH:mm:ss',
  'yyyyལོའི་ཟླ MMM d EEEE',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy.MM.dd HH:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yyyy\'ལོའི་ཟླ་\' M',
  'yyyy-M-d HH:mm:ss',
  'yyyy.M.d HH:mm:ss',
  'yyyy/M/d HH:mm:ss',
  'yyyyལོའི་ཟླ MMM d',
  'yy-M-d HH:mm:ss',
  'yy.M.d HH:mm:ss',
  'yy/M/d HH:mm:ss',
  'yyyy-MM-dd',
  'yyyy.MM.dd',
  'yyyy/MM/dd',
  'yyyy-M-d',
  'yyyy.M.d',
  'yyyy/M/d',
  'y-MM-dd',
  'yy-M-d',
  'yy.M.d',
  'yy/M/d',
  'yyyy.M'
];