formats["ca-es"] = [
  'EEEE, d\' / \'MMMM\' / \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'd\' \'MMMM\' \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'd\'/\'MMMM\'/\'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, d\' / \'MMMM\' / \'yyyy HH\'H\'mm\'\'\'\'',
  'dd/MM/yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'dd-MM-yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'dd.MM.yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'dd/MM/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'd/MM/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, d\' / \'MMMM\' / \'yyyy HH:mm:ss',
  'd/M/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, d\' / \'MMMM\' / \'yyyy H:mm:ss',
  'd\' \'MMMM\' \'yyyy HH\'H\'mm\'\'\'\'',
  'd\'/\'MMMM\'/\'yyyy HH\'H\'mm\'\'\'\'',
  'EEEE, d\' / \'MMMM\' / \'yyyy HH:mm',
  'EEEE, d\' / \'MMMM\' / \'yyyy H:mm',
  'HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, d\' / \'MMMM\' / \'yyyy',
  'd\' \'MMMM\' \'yyyy HH:mm:ss',
  'd\'/\'MMMM\'/\'yyyy HH:mm:ss',
  'dd/MM/yyyy HH\'H\'mm\'\'\'\'',
  'd\' \'MMMM\' \'yyyy H:mm:ss',
  'd\'/\'MMMM\'/\'yyyy H:mm:ss',
  'dd-MM-yy HH\'H\'mm\'\'\'\'',
  'dd.MM.yy HH\'H\'mm\'\'\'\'',
  'dd/MM/yy HH\'H\'mm\'\'\'\'',
  'd/MM/yy HH\'H\'mm\'\'\'\'',
  'd\' \'MMMM\' \'yyyy HH:mm',
  'd\'/\'MMMM\'/\'yyyy HH:mm',
  'd/M/yy HH\'H\'mm\'\'\'\'',
  'd\' \'MMMM\' \'yyyy H:mm',
  'd\'/\'MMMM\'/\'yyyy H:mm',
  'EEEE, d MMMM \'de\' y',
  'd\' \'MMMM\' \'yyyy',
  'd\'/\'MMMM\'/\'yyyy',
  'dd/MM/yyyy HH:mm:ss',
  'dd/MM/yyyy H:mm:ss',
  'HH\'H\'mm\'\'\'\'',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MMMM\' de \'yyyy',
  'd/MM/yy HH:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yyyy HH:mm',
  'MMMM\' / \'yyyy',
  'd MMMM \'de\' y',
  'd/M/yy HH:mm:ss',
  'd/MM/yy H:mm:ss',
  'dd/MM/yyyy H:mm',
  'd/M/yy H:mm:ss',
  'dd-MM-yy HH:mm',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'd/MM/yy HH:mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'H:mm:ss zzzz',
  'd/M/yy HH:mm',
  'd/MM/yy H:mm',
  'd/M/yy H:mm',
  'dd/MM/yyyy',
  'H:mm:ss z',
  'HH:mm:ss',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'd/MM/yy',
  'dd MMMM',
  'd/M/yy',
  'HH:mm',
  'H:mm',
  'yyyy-MM-dd HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH\'H\'mm\'\'\'\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];