formats["cs-cz"] = [
  'd. MMMM yyyy h.mm.ss a',
  'd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy H.mm.ss',
  'd. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy h.mm a',
  'd. MMMM yyyy HH:mm',
  'd.M.yyyy h.mm.ss a',
  'd. MMMM yyyy H.mm',
  'd. MMMM yyyy H:mm',
  'd.M.yyyy HH:mm:ss',
  'd-M-yy h.mm.ss a',
  'd.M.yyyy H.mm.ss',
  'd.M.yyyy H:mm:ss',
  'd-M-yy HH:mm:ss',
  'd.M.yyyy h.mm a',
  'EEEE d. MMMM y',
  'd-M-yy H.mm.ss',
  'd-M-yy H:mm:ss',
  'd.M.yyyy HH:mm',
  'd-M-yy h.mm a',
  'd.M.yyyy H.mm',
  'd.M.yyyy H:mm',
  'H:mm:ss zzzz',
  'd-M-yy HH:mm',
  'd. MMMM yyyy',
  'd-M-yy H.mm',
  'd-M-yy H:mm',
  'H:mm:ss z',
  'MMMM yyyy',
  'd. MMMM y',
  'h.mm.ss a',
  'HH:mm:ss',
  'd.M.yyyy',
  'dd.MM.yy',
  'H.mm.ss',
  'H:mm:ss',
  'd. M. y',
  'dd MMMM',
  'd-M-yy',
  'h.mm a',
  'HH:mm',
  'H.mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd h.mm.ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-M-d h.mm.ss a',
  'yyyy-MM-dd H.mm.ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-M-d HH:mm:ss',
  'yyyy-MM-dd h.mm a',
  'yy-M-d h.mm.ss a',
  'yyyy-M-d H.mm.ss',
  'yyyy-M-d H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yy-M-d HH:mm:ss',
  'yyyy-M-d h.mm a',
  'yyyy-MM-dd H.mm',
  'yyyy-MM-dd H:mm',
  'yy-M-d H.mm.ss',
  'yy-M-d H:mm:ss',
  'yyyy-M-d HH:mm',
  'yy-M-d h.mm a',
  'yyyy-M-d H.mm',
  'yyyy-M-d H:mm',
  'yy-M-d HH:mm',
  'yy-M-d H.mm',
  'yy-M-d H:mm',
  'yyyy-MM-dd',
  'yyyy-M-d',
  'yy-M-d'
];