formats["da-dk"] = [
  'EEEE \'den\' d. MMMM y',
  'dd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy H:mm:ss',
  'dd-MM-yyyy HH:mm:ss',
  'dd. MMMM yyyy HH:mm',
  'd. MMMM yyyy HH:mm',
  'dd-MM-yyyy H:mm:ss',
  'dd. MMMM yyyy H:mm',
  'd. MMMM yyyy H:mm',
  'dd-MM-yy HH:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd-MM-yyyy HH:mm',
  'dd-MM-yyyy H:mm',
  'dd-MM-yy HH:mm',
  'HH.mm.ss zzzz',
  'dd-MM-yy H:mm',
  'dd. MMMM yyyy',
  'd. MMMM yyyy',
  'HH.mm.ss z',
  'dd-MM-yyyy',
  'MMMM yyyy',
  'd. MMMM y',
  'HH.mm.ss',
  'HH:mm:ss',
  'd. MMM y',
  'dd-MM-yy',
  'H:mm:ss',
  'd. MMMM',
  'dd/MM/y',
  'HH.mm',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy MM dd HH:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy MM dd H:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy MM dd HH:mm',
  'yyyy-MM-dd HH:mm',
  'yyyy MM dd H:mm',
  'yyyy-MM-dd H:mm',
  'yyyy MM dd',
  'yyyy-MM-dd'
];