formats["de-at"] = [
  'EEEE, dd. MMMM yyyy HH:mm\' Uhr\'',
  'EEEE, dd. MMMM yyyy HH:mm:ss',
  'EEEE, dd. MMMM yyyy H:mm:ss',
  'EEEE, dd. MMMM yyyy HH:mm',
  'd.MMMM yyyy HH:mm\' Uhr\'',
  'EEEE, dd. MMMM yyyy H:mm',
  'd MMM yyyy HH:mm\' Uhr\'',
  'dd.MM.yyyy HH:mm\' Uhr\'',
  'd.MMMyyyy HH:mm\' Uhr\'',
  'dd.M.yyyy HH:mm\' Uhr\'',
  'dd.MM.yy HH:mm\' Uhr\'',
  'd.MMMM yyyy HH:mm:ss',
  'EEEE, dd. MMMM yyyy',
  'd MMM yyyy HH:mm:ss',
  'd.MMMM yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'd MMM yyyy H:mm:ss',
  'd.MMMyyyy HH:mm:ss',
  'dd.M.yyyy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'd.MMMM yyyy HH:mm',
  'd.MMMyyyy H:mm:ss',
  'dd.M.yyyy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'd MMM yyyy HH:mm',
  'd.MMMM yyyy H:mm',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'EEEE, d. MMMM y',
  'd MMM yyyy H:mm',
  'd.MMMyyyy HH:mm',
  'dd.M.yyyy HH:mm',
  'dd.MM.yyyy H:mm',
  'd.MMMyyyy H:mm',
  'dd.M.yyyy H:mm',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'HH:mm\' Uhr\'',
  'dd.MM.yy H:mm',
  'd.MMMM yyyy',
  'HH:mm:ss z',
  'd MMM yyyy',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'd. MMMM y',
  'd.MMMyyyy',
  'dd.M.yyyy',
  'HH:mm:ss',
  'dd.MM.yy',
  'H:mm:ss',
  'dd MMMM',
  'dd.MM.y',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm\' Uhr\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];