formats["de-ch"] = [
  'EEEE, d. MMMM yyyy H.mm\' Uhr\'',
  'EEEE, d. MMMM yyyy HH.mm\' h\'',
  'EEEE, d. MMMM yyyy H.mm\' h\'',
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy H.mm\' Uhr\'',
  'EEEE, d. MMMM yyyy HH:mm',
  'd. MMMM yyyy HH.mm\' h\'',
  'EEEE, d. MMMM yyyy H:mm',
  'd. MMMM yyyy H.mm\' h\'',
  'dd.MM.yyyy H.mm\' Uhr\'',
  'd. MMM yy H.mm\' Uhr\'',
  'dd. M. yy H.mm\' Uhr\'',
  'dd.MM.yyyy HH.mm\' h\'',
  'd. MMM yy HH.mm\' h\'',
  'd. MMMM yyyy HH:mm:ss',
  'dd. M. yy HH.mm\' h\'',
  'dd.MM.yy H.mm\' Uhr\'',
  'dd.MM.yyyy H.mm\' h\'',
  'd. MMM yy H.mm\' h\'',
  'd. MMMM yyyy H:mm:ss',
  'd.MM.yy H.mm\' Uhr\'',
  'dd. M. yy H.mm\' h\'',
  'dd.MM.yy HH.mm\' h\'',
  'd.M.yy H.mm\' Uhr\'',
  'd.MM.yy HH.mm\' h\'',
  'dd.MM.yy H.mm\' h\'',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy',
  'd. MMM yy HH:mm:ss',
  'd. MMMM yyyy HH:mm',
  'd.M.yy HH.mm\' h\'',
  'd.MM.yy H.mm\' h\'',
  'dd. M. yy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'd. MMM yy H:mm:ss',
  'd. MMMM yyyy H:mm',
  'd.M.yy H.mm\' h\'',
  'dd. M. yy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'd.MM.yy HH:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'EEEE, d. MMMM y',
  'd. MMM yy HH:mm',
  'd.M.yy HH:mm:ss',
  'd.MM.yy H:mm:ss',
  'dd. M. yy HH:mm',
  'dd.MM.yyyy H:mm',
  'd. MMM yy H:mm',
  'd.M.yy H:mm:ss',
  'dd. M. yy H:mm',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'd.MM.yy HH:mm',
  'dd.MM.yy H:mm',
  'H.mm\' Uhr\'',
  'd. MMMM yyyy',
  'd.M.yy HH:mm',
  'd.MM.yy H:mm',
  'HH.mm\' h\'',
  'd.M.yy H:mm',
  'H.mm\' h\'',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'd. MMM yy',
  'd. MMMM y',
  'dd. M. yy',
  'HH:mm:ss',
  'dd.MM.yy',
  'H:mm:ss',
  'd.MM.yy',
  'dd MMMM',
  'dd.MM.y',
  'd.M.yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd H.mm\' Uhr\'',
  'yyyy-MM-dd HH.mm\' h\'',
  'yyyy-MM-dd H.mm\' h\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];