formats["de-lu"] = [
  'EEEE, d. MMMM yyyy H.mm\' Uhr \'',
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy H.mm\' Uhr \'',
  'd. MMM yyyy H.mm\' Uhr \'',
  'EEEE, d. MMMM yyyy HH:mm',
  'dd.MM.yyyy H.mm\' Uhr \'',
  'EEEE, d. MMMM yyyy H.mm',
  'EEEE, d. MMMM yyyy H:mm',
  'd.M.yyyy H.mm\' Uhr \'',
  'dd.MM.yy H.mm\' Uhr \'',
  'd. MMMM yyyy HH:mm:ss',
  'd.MM.yy H.mm\' Uhr \'',
  'd. MMM yyyy HH:mm:ss',
  'd. MMMM yyyy H:mm:ss',
  'd.M.yy H.mm\' Uhr \'',
  'd. MMM yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy',
  'd. MMMM yyyy HH:mm',
  'dd.MM.yyyy H:mm:ss',
  'd. MMM yyyy HH:mm',
  'd. MMMM yyyy H.mm',
  'd. MMMM yyyy H:mm',
  'd.M.yyyy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'd. MMM yyyy H.mm',
  'd. MMM yyyy H:mm',
  'd.M.yyyy H:mm:ss',
  'd.MM.yy HH:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'EEEE, d. MMMM y',
  'd.M.yy HH:mm:ss',
  'd.MM.yy H:mm:ss',
  'dd.MM.yyyy H.mm',
  'dd.MM.yyyy H:mm',
  'd.M.yy H:mm:ss',
  'd.M.yyyy HH:mm',
  'dd.MM.yy HH:mm',
  'H.mm\' Uhr \'',
  'HH:mm:ss zzzz',
  'd.M.yyyy H.mm',
  'd.M.yyyy H:mm',
  'd.MM.yy HH:mm',
  'dd.MM.yy H.mm',
  'dd.MM.yy H:mm',
  'd. MMMM yyyy',
  'd.M.yy HH:mm',
  'd.MM.yy H.mm',
  'd.MM.yy H:mm',
  'd. MMM yyyy',
  'd.M.yy H.mm',
  'd.M.yy H:mm',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'd. MMMM y',
  'HH:mm:ss',
  'd.M.yyyy',
  'dd.MM.yy',
  'H:mm:ss',
  'd.MM.yy',
  'dd MMMM',
  'dd.MM.y',
  'd.M.yy',
  'HH:mm',
  'H.mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd H.mm\' Uhr \'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H.mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];