formats["dsb-de"] = [
  'EEEE, d. MMMM yyyy \'zeger \'H:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss\' góź.\'',
  'd. MMMM yyyy \'zeger \'H:mm:ss',
  'd. MMMM yyyy H:mm:ss\' góź.\'',
  'd. M. yyyy \'zeger \'H:mm:ss',
  'dd.MM.yyyy \'zeger \'H:mm:ss',
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'd. M. yyyy H:mm:ss\' góź.\'',
  'dd.MM.yyyy H:mm:ss\' góź.\'',
  'd. M. yy \'zeger \'H:mm:ss',
  'dd.MM.yy \'zeger \'H:mm:ss',
  'd. M. yy H:mm:ss\' góź.\'',
  'dd.MM.yy H:mm:ss\' góź.\'',
  'd. MMMM yyyy HH:mm:ss',
  'd. M. yyyy HH:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy',
  '\'zeger \'H:mm:ss',
  'd. M. yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'H:mm:ss\' góź.\'',
  'EEEE, d. MMMM y',
  'H:mm:ss zzzz',
  'd. MMMM yyyy',
  'd. M. yyyy',
  'dd.MM.yyyy',
  'H:mm:ss z',
  'MMMM yyyy',
  'd. MMMM y',
  'HH:mm:ss',
  'd. M. yy',
  'dd.MM.yy',
  'H:mm:ss',
  'MMMM dd',
  'd.M.yy',
  'd.M.y',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd \'zeger \'H:mm:ss',
  'yyyy-MM-dd H:mm:ss\' góź.\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd'
];