formats["dz-bt"] = [
  'ཆུ་ཚོད་ h སྐར་མ་ mm:ss a zzzz',
  'སྤྱི་ལོ་y ཟླ་MMM ཚེས་dd',
  'ཆུ་ཚོད་ h སྐར་མ་ mm:ss a z',
  'EEEE, སྤྱི་ལོ་y MMMM ཚེས་dd',
  'EEEE, སྤྱི་ལོ་yyyy MMMM ཚེས་dd ཆུ་ཚོད་h:mm:ss a',
  'ཆུ་ཚོད་ h སྐར་མ་ mm a',
  'སྤྱི་ལོ་y MMMM ཚེས་ dd',
  'སྤྱི་ལོ་yyyy ཟླ་MMM ཚེས་dd ཆུ་ཚོད་h:mm:ss a',
  'སྤྱི་ལོ་yyyy MMMM ཚེས་ dd ཆུ་ཚོད་h:mm:ss a',
  'EEEE, སྤྱི་ལོ་yyyy MMMM ཚེས་dd HH:mm:ss',
  'སྤྱི་ལོ་yyyy ཟླ་MMM ཚེས་dd HH:mm:ss',
  'སྤྱི་ལོ་yyyy MMMM ཚེས་ dd HH:mm:ss',
  'EEEE, སྤྱི་ལོ་yyyy MMMM ཚེས་dd',
  'ཆུ་ཚོད་h:mm:ss a',
  'སྤྱི་ལོ་yyyy ཟླ་MMM ཚེས་dd',
  'སྤྱི་ལོ་yyyy MMMM ཚེས་ dd',
  'HH:mm:ss',
  'MMMM dd',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd ཆུ་ཚོད་h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy སྤྱི་ཟླ་MMMM',
  'yyyy-MM-dd',
  'y-MM-dd'
];