formats["el-gr"] = [
  'EEEE, d MMMM yyyy hh:mm:ss a',
  'EEEE, d MMMM yyyy h:mm:ss a',
  'EEEE, d MMMM yyyy HH:mm:ss',
  'EEEE, d MMMM yyyy H:mm:ss',
  'EEEE, d MMMM yyyy hh:mm a',
  'EEEE, d MMMM yyyy h:mm a',
  'EEEE, d MMMM yyyy HH:mm',
  'EEEE, d MMMM yyyy H:mm',
  'd MMMM yyyy hh:mm:ss a',
  'd MMMM yyyy h:mm:ss a',
  'dd/MM/yyyy hh:mm:ss a',
  'd MMMM yyyy HH:mm:ss',
  'dd/MM/yyyy h:mm:ss a',
  'd MMMM yyyy H:mm:ss',
  'd MMMM yyyy hh:mm a',
  'd/M/yyyy hh:mm:ss a',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'd MMMM yyyy h:mm a',
  'd/M/yyyy h:mm:ss a',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'EEEE, d MMMM yyyy',
  'd MMMM yyyy HH:mm',
  'd/M/yy hh:mm:ss a',
  'd/M/yyyy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yyyy h:mm a',
  'd MMMM yyyy H:mm',
  'd/M/yy h:mm:ss a',
  'd/M/yyyy H:mm:ss',
  'd/M/yyyy hh:mm a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'd/M/yy HH:mm:ss',
  'd/M/yyyy h:mm a',
  'dd/MM/yy h:mm a',
  'dd/MM/yyyy H:mm',
  'EEEE, d MMMM y',
  'd/M/yy H:mm:ss',
  'd/M/yy hh:mm a',
  'd/M/yyyy HH:mm',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'd/M/yy h:mm a',
  'd/M/yyyy H:mm',
  'dd/MM/yy H:mm',
  'd/M/yy HH:mm',
  'd MMMM yyyy',
  'd/M/yy H:mm',
  'h:mm:ss a z',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'd/M/yyyy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'dd MMMM',
  'hh:mm a',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];