formats["en-au"] = [
  'EEEE, d MMMM yyyy h:mm:ss a',
  'EEEE, d MMMM yyyy HH:mm:ss',
  'EEEE, d MMMM yyyy H:mm:ss',
  'EEEE, d MMMM yyyy h:mm a',
  'EEEE, d MMMM yyyy HH:mm',
  'EEEE, d MMMM yyyy H:mm',
  'dd-MMMM-yyyy h:mm:ss a',
  'd MMMM yyyy h:mm:ss a',
  'dd-MMMM-yyyy HH:mm:ss',
  'd MMMM yyyy HH:mm:ss',
  'dd-MMMM-yyyy H:mm:ss',
  'dd/MM/yyyy h:mm:ss a',
  'd MMMM yyyy H:mm:ss',
  'd/MM/yyyy h:mm:ss a',
  'dd-MMM-yy h:mm:ss a',
  'dd-MMMM-yyyy h:mm a',
  'dd/MM/yyyy HH:mm:ss',
  'd MMMM yyyy h:mm a',
  'd/M/yyyy h:mm:ss a',
  'd/MM/yyyy HH:mm:ss',
  'dd-MMM-yy HH:mm:ss',
  'dd-MMMM-yyyy HH:mm',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'EEEE, d MMMM yyyy',
  'd MMMM yyyy HH:mm',
  'd/M/yyyy HH:mm:ss',
  'd/MM/yy h:mm:ss a',
  'd/MM/yyyy H:mm:ss',
  'dd-MMM-yy H:mm:ss',
  'dd-MMMM-yyyy H:mm',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yyyy h:mm a',
  'd MMMM yyyy H:mm',
  'd/M/yy h:mm:ss a',
  'd/M/yyyy H:mm:ss',
  'd/MM/yy HH:mm:ss',
  'd/MM/yyyy h:mm a',
  'dd-MMM-yy h:mm a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yyyy HH:mm',
  'd/M/yy HH:mm:ss',
  'd/M/yyyy h:mm a',
  'd/MM/yy H:mm:ss',
  'd/MM/yyyy HH:mm',
  'dd-MMM-yy HH:mm',
  'dd/MM/yy h:mm a',
  'dd/MM/yyyy H:mm',
  'EEEE, d MMMM y',
  'd/M/yy H:mm:ss',
  'd/M/yyyy HH:mm',
  'd/MM/yy h:mm a',
  'd/MM/yyyy H:mm',
  'dd-MMM-yy H:mm',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'd/M/yy h:mm a',
  'd/M/yyyy H:mm',
  'd/MM/yy HH:mm',
  'dd/MM/yy H:mm',
  'd/M/yy HH:mm',
  'd/MM/yy H:mm',
  'dd-MMMM-yyyy',
  'd MMMM yyyy',
  'd/M/yy H:mm',
  'h:mm:ss a z',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'd/MM/yyyy',
  'dd-MMM-yy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'd/M/yyyy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'd/MM/yy',
  'dd MMMM',
  'd/M/yy',
  'd/MM/y',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy/MM/dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yy/MM/dd h:mm:ss a',
  'yyyy-MM-dd H:mm:ss',
  'yyyy/MM/dd H:mm:ss',
  'yy/MM/dd HH:mm:ss',
  'yyyy-MM-dd h:mm a',
  'yyyy/MM/dd h:mm a',
  'yy/MM/dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy/MM/dd HH:mm',
  'yy/MM/dd h:mm a',
  'yyyy-MM-dd H:mm',
  'yyyy/MM/dd H:mm',
  'yy/MM/dd HH:mm',
  'yy/MM/dd H:mm',
  'yyyy-MM-dd',
  'yyyy/MM/dd',
  'yy/MM/dd'
];