formats["en-bz"] = [
  'dddd, dd MMMM yyyy hh:mm:ss a',
  'dddd, dd MMMM yyyy HH:mm:ss',
  'dddd, dd MMMM yyyy hh:mm a',
  'dddd, dd MMMM yyyy HH:mm',
  'dd/MM/yyyy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'dddd, dd MMMM yyyy',
  'dd/MM/yyyy HH:mm',
  'EEEE, dd MMMM y',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM yyyy',
  'dd MMMM y',
  'HH:mm:ss',
  'dd-MMM-y',
  'dd/MM/yy',
  'dd MMMM',
  'hh:mm a',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd'
];