formats["en-ca"] = [
  'MMMM d, yyyy hh:mm:ss a',
  'MMMM d, yyyy h:mm:ss a',
  'MMMM d, yyyy HH:mm:ss',
  'dd/MM/yyyy hh:mm:ss a',
  'MMMM d, yyyy H:mm:ss',
  'MMMM d, yyyy hh:mm a',
  'dd/MM/yyyy h:mm:ss a',
  'MMMM d, yyyy h:mm a',
  'd-MMM-yy hh:mm:ss a',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'M/dd/yy hh:mm:ss a',
  'MMMM d, yyyy HH:mm',
  'd-MMM-yy h:mm:ss a',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'M/dd/yy h:mm:ss a',
  'MMMM d, yyyy H:mm',
  'd-MMM-yy HH:mm:ss',
  'd/M/yy hh:mm:ss a',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yyyy h:mm a',
  'M/dd/yy HH:mm:ss',
  'd-MMM-yy H:mm:ss',
  'd-MMM-yy hh:mm a',
  'd/M/yy h:mm:ss a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'EEEE, MMMM d, y',
  'M/dd/yy H:mm:ss',
  'M/dd/yy hh:mm a',
  'd-MMM-yy h:mm a',
  'd/M/yy HH:mm:ss',
  'dd/MM/yy h:mm a',
  'dd/MM/yyyy H:mm',
  'M/dd/yy h:mm a',
  'd-MMM-yy HH:mm',
  'd/M/yy H:mm:ss',
  'd/M/yy hh:mm a',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'M/dd/yy HH:mm',
  'd-MMM-yy H:mm',
  'd/M/yy h:mm a',
  'dd/MM/yy H:mm',
  'M/dd/yy H:mm',
  'MMMM d, yyyy',
  'd/M/yy HH:mm',
  'd/M/yy H:mm',
  'h:mm:ss a z',
  'MMMM, yyyy',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM d, y',
  'h:mm:ss a',
  'HH:mm:ss',
  'MMM d, y',
  'd-MMM-yy',
  'dd/MM/yy',
  'H:mm:ss',
  'M/dd/yy',
  'MMMM dd',
  'hh:mm a',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yy-MM-dd h:mm:ss a',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yy-MM-dd HH:mm:ss',
  'yyyy-MM-dd h:mm a',
  'yy-MM-dd H:mm:ss',
  'yy-MM-dd hh:mm a',
  'yyyy-MM-dd HH:mm',
  'yy-MM-dd h:mm a',
  'yyyy-MM-dd H:mm',
  'yy-MM-dd HH:mm',
  'yy-MM-dd H:mm',
  'yyyy-MM-dd',
  'yy-MM-dd',
  'y-MM-dd'
];