formats["en-gb"] = [
  'dd MMMM yyyy hh:mm:ss a',
  'd MMMM yyyy hh:mm:ss a',
  'dd MMMM yyyy h:mm:ss a',
  'd MMMM yyyy h:mm:ss a',
  'dd MMMM yyyy HH:mm:ss',
  'dd/MM/yyyy hh:mm:ss a',
  'd MMMM yyyy HH:mm:ss',
  'dd MMMM yyyy H:mm:ss',
  'dd MMMM yyyy hh:mm a',
  'dd/MM/yyyy h:mm:ss a',
  'd MMMM yyyy H:mm:ss',
  'd MMMM yyyy hh:mm a',
  'dd MMMM yyyy h:mm a',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'd MMMM yyyy h:mm a',
  'dd MMMM yyyy HH:mm',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'd MMMM yyyy HH:mm',
  'd.M.yy hh:mm:ss a',
  'd/M/yy hh:mm:ss a',
  'dd MMMM yyyy H:mm',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yyyy h:mm a',
  'd MMMM yyyy H:mm',
  'd.M.yy h:mm:ss a',
  'd/M/yy h:mm:ss a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'd.M.yy HH:mm:ss',
  'd/M/yy HH:mm:ss',
  'dd/MM/yy h:mm a',
  'dd/MM/yyyy H:mm',
  'EEEE, d MMMM y',
  'd.M.yy H:mm:ss',
  'd.M.yy hh:mm a',
  'd/M/yy H:mm:ss',
  'd/M/yy hh:mm a',
  'dd/MM/yy HH:mm',
  'HH:mm:ss zzzz',
  'd.M.yy h:mm a',
  'd/M/yy h:mm a',
  'dd/MM/yy H:mm',
  'd.M.yy HH:mm',
  'd/M/yy HH:mm',
  'dd MMMM yyyy',
  'd MMMM yyyy',
  'd.M.yy H:mm',
  'd/M/yy H:mm',
  'HH:mm:ss z',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'dd MMMM',
  'dd/MM/y',
  'hh:mm a',
  'd.M.yy',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];