formats["en-ie"] = [
  'dd MMMM yyyy HH:mm:ss',
  'd MMMM yyyy HH:mm:ss',
  'dd MMMM yyyy H:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'dd MMMM yyyy HH:mm',
  'dd/MM/yyyy H:mm:ss',
  'd MMMM yyyy HH:mm',
  'dd MMMM yyyy H:mm',
  'dd/MM/yy HH:mm:ss',
  'd MMMM yyyy H:mm',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yyyy HH:mm',
  'd.M.yy HH:mm:ss',
  'd/M/yy HH:mm:ss',
  'dd/MM/yyyy H:mm',
  'd.M.yy H:mm:ss',
  'd/M/yy H:mm:ss',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'EEEE d MMMM y',
  'dd/MM/yy H:mm',
  'd.M.yy HH:mm',
  'd/M/yy HH:mm',
  'dd MMMM yyyy',
  'd MMMM yyyy',
  'd.M.yy H:mm',
  'd/M/yy H:mm',
  'h:mm:ss a z',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'dd MMMM',
  'dd/MM/y',
  'd.M.yy',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];