formats["en-in"] = [
  'dd MMMM yyyy hh:mm:ss a',
  'd MMMM yyyy hh:mm:ss a',
  'dd MMMM yyyy h.mm.ss a',
  'd MMMM yyyy h.mm.ss a',
  'dd MMMM yyyy HH:mm:ss',
  'dd-MM-yyyy hh:mm:ss a',
  'd MMMM yyyy HH:mm:ss',
  'dd MMMM yyyy H:mm:ss',
  'dd-MM-yyyy h.mm.ss a',
  'd MMMM yyyy H:mm:ss',
  'dd-MM-yy hh:mm:ss a',
  'dd-MM-yyyy HH:mm:ss',
  'dd-MM-yy h.mm.ss a',
  'dd-MM-yyyy H:mm:ss',
  'd-M-yy hh:mm:ss a',
  'd.M.yy hh:mm:ss a',
  'dd-MM-yy HH:mm:ss',
  'd-M-yy h.mm.ss a',
  'd.M.yy h.mm.ss a',
  'dd-MM-yy H:mm:ss',
  'd-M-yy HH:mm:ss',
  'd.M.yy HH:mm:ss',
  'd-M-yy H:mm:ss',
  'd.M.yy H:mm:ss',
  'h:mm:ss a zzzz',
  'EEEE d MMMM y',
  'dd MMMM yyyy',
  'd MMMM yyyy',
  'h:mm:ss a z',
  'MMMM, yyyy',
  'dd-MM-yyyy',
  'hh:mm:ss a',
  'h.mm.ss a',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'dd-MM-yy',
  'dd-MMM-y',
  'dd/MM/yy',
  'H:mm:ss',
  'MMMM dd',
  'd-M-yy',
  'd.M.yy',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h.mm.ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd'
];