formats["en-jm"] = [
  'dddd, MMMM dd, yyyy hh:mm:ss a',
  'dddd, dd MMMM, yyyy hh:mm:ss a',
  'dddd, MMMM dd, yyyy h:mm:ss a',
  'dddd, dd MMMM, yyyy h:mm:ss a',
  'dddd, MMMM dd, yyyy HH:mm:ss',
  'dddd, dd MMMM, yyyy HH:mm:ss',
  'dddd, MMMM dd, yyyy H:mm:ss',
  'dddd, MMMM dd, yyyy hh:mm a',
  'dddd, dd MMMM, yyyy H:mm:ss',
  'dddd, dd MMMM, yyyy hh:mm a',
  'dddd, MMMM dd, yyyy h:mm a',
  'dddd, dd MMMM, yyyy h:mm a',
  'dddd, MMMM dd, yyyy HH:mm',
  'dddd, dd MMMM, yyyy HH:mm',
  'MMMM dd, yyyy hh:mm:ss a',
  'dd MMMM, yyyy hh:mm:ss a',
  'dddd, MMMM dd, yyyy H:mm',
  'dddd, dd MMMM, yyyy H:mm',
  'MMMM dd, yyyy h:mm:ss a',
  'dd MMMM, yyyy h:mm:ss a',
  'MMMM dd, yyyy HH:mm:ss',
  'dd MMMM, yyyy HH:mm:ss',
  'MMMM dd, yyyy H:mm:ss',
  'MMMM dd, yyyy hh:mm a',
  'dd MMMM, yyyy H:mm:ss',
  'dd MMMM, yyyy hh:mm a',
  'dd/MM/yyyy hh:mm:ss a',
  'MMMM dd, yyyy h:mm a',
  'dd MMMM, yyyy h:mm a',
  'dd/MM/yyyy h:mm:ss a',
  'MMMM dd, yyyy HH:mm',
  'dd MMMM, yyyy HH:mm',
  'dd/MM/yyyy HH:mm:ss',
  'dddd, MMMM dd, yyyy',
  'dddd, dd MMMM, yyyy',
  'MMMM dd, yyyy H:mm',
  'dd MMMM, yyyy H:mm',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'dd/MM/yyyy h:mm a',
  'dd/MM/yyyy HH:mm',
  'dd/MM/yyyy H:mm',
  'EEEE, d MMMM y',
  'h:mm:ss a zzzz',
  'MMMM dd, yyyy',
  'dd MMMM, yyyy',
  'h:mm:ss a z',
  'MMMM, yyyy',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'H:mm:ss',
  'MMMM dd',
  'd MMM y',
  'hh:mm a',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];