formats["en-my"] = [
  'EEEE, d MMMM, yyyy hh:mm:ss a',
  'EEEE, d MMMM, yyyy h:mm:ss a',
  'EEEE, d MMMM, yyyy HH:mm:ss',
  'EEEE, d MMMM, yyyy H:mm:ss',
  'd MMMM, yyyy hh:mm:ss a',
  'd MMMM, yyyy h:mm:ss a',
  'd MMMM, yyyy HH:mm:ss',
  'dd/MM/yyyy hh:mm:ss a',
  'd MMMM, yyyy H:mm:ss',
  'dd/MM/yyyy h:mm:ss a',
  'd/M/yyyy hh:mm:ss a',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'EEEE, d MMMM, yyyy',
  'd/M/yyyy h:mm:ss a',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'd/M/yy hh:mm:ss a',
  'd/M/yyyy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'd/M/yy h:mm:ss a',
  'd/M/yyyy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'd/M/yy HH:mm:ss',
  'EEEE, d MMMM y',
  'd/M/yy H:mm:ss',
  'h:mm:ss a zzzz',
  'd MMMM, yyyy',
  'h:mm:ss a z',
  'MMMM, yyyy',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'd/M/yyyy',
  'dd/MM/yy',
  'H:mm:ss',
  'MMMM dd',
  'd MMM y',
  'dd/MM/y',
  'd/M/yy',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd'
];