formats["en-nz"] = [
  'EEEE, d MMMM yyyy hh:mm:ss a',
  'EEEE, d MMMM yyyy h:mm:ss a',
  'EEEE, d MMMM yyyy HH:mm:ss',
  'EEEE, d MMMM yyyy H:mm:ss',
  'EEEE, d MMMM yyyy hh:mm a',
  'EEEE, d MMMM yyyy h:mm a',
  'EEEE, d MMMM yyyy HH:mm',
  'EEEE, d MMMM yyyy H:mm',
  'd MMMM yyyy hh:mm:ss a',
  'd MMMM yyyy h:mm:ss a',
  'd MMMM yyyy HH:mm:ss',
  'd/MM/yyyy hh:mm:ss a',
  'd MMMM yyyy H:mm:ss',
  'd MMMM yyyy hh:mm a',
  'd/MM/yyyy h:mm:ss a',
  'dd/MM/yy hh:mm:ss a',
  'd MMMM yyyy h:mm a',
  'd.MM.yy hh:mm:ss a',
  'd/MM/yy hh:mm:ss a',
  'd/MM/yyyy HH:mm:ss',
  'dd/MM/yy h:mm:ss a',
  'EEEE, d MMMM yyyy',
  'd MMMM yyyy HH:mm',
  'd.MM.yy h:mm:ss a',
  'd/MM/yy h:mm:ss a',
  'd/MM/yyyy H:mm:ss',
  'd/MM/yyyy hh:mm a',
  'dd/MM/yy HH:mm:ss',
  'd MMMM yyyy H:mm',
  'd.MM.yy HH:mm:ss',
  'd/MM/yy HH:mm:ss',
  'd/MM/yyyy h:mm a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'd.MM.yy H:mm:ss',
  'd.MM.yy hh:mm a',
  'd/MM/yy H:mm:ss',
  'd/MM/yy hh:mm a',
  'd/MM/yyyy HH:mm',
  'dd/MM/yy h:mm a',
  'EEEE, d MMMM y',
  'd.MM.yy h:mm a',
  'd/MM/yy h:mm a',
  'd/MM/yyyy H:mm',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'd.MM.yy HH:mm',
  'd/MM/yy HH:mm',
  'dd/MM/yy H:mm',
  'd.MM.yy H:mm',
  'd/MM/yy H:mm',
  'd MMMM yyyy',
  'h:mm:ss a z',
  'hh:mm:ss a',
  'MMMM yyyy',
  'd/MM/yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'dd/MM/yy',
  'H:mm:ss',
  'd.MM.yy',
  'd/MM/yy',
  'dd MMMM',
  'hh:mm a',
  'd/MM/y',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];