formats["en-tt"] = [
  'EEEE, dd MMMM yyyy hh:mm:ss a',
  'EEEE, dd MMMM yyyy HH:mm:ss',
  'EEEE, dd MMMM yyyy hh:mm a',
  'EEEE, dd MMMM yyyy HH:mm',
  'dd/MM/yyyy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'EEEE, dd MMMM yyyy',
  'dd/MM/yyyy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'EEEE, d MMMM y',
  'h:mm:ss a zzzz',
  'h:mm:ss a z',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'd MMM y',
  'dd MMMM',
  'dd/MM/y',
  'hh:mm a',
  'h:mm a',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd'
];