formats["en-za"] = [
  'dd MMMM yyyy hh:mm:ss a',
  'dd MMMM yyyy HH:mm:ss',
  'dd MMMM yyyy hh:mm a',
  'dd MMMM yyyy HH:mm',
  'EEEE, dd MMMM y',
  'h:mm:ss a zzzz',
  'dd MMMM yyyy',
  'h:mm:ss a z',
  'hh:mm:ss a',
  'MMMM yyyy',
  'dd MMMM y',
  'h:mm:ss a',
  'HH:mm:ss',
  'dd MMM y',
  'dd MMMM',
  'hh:mm a',
  'h:mm a',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy/MM/dd hh:mm:ss a',
  'yy/MM/dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy/MM/dd hh:mm a',
  'yy/MM/dd HH:mm:ss',
  'yy/MM/dd hh:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy/MM/dd HH:mm',
  'yy/MM/dd HH:mm',
  'yyyy-MM-dd',
  'yyyy/MM/dd',
  'yy/MM/dd',
  'y/MM/dd'
];