formats["es-cl"] = [
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm',
  'd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE, d \'de\' MMMM \'de\' y',
  'd\' de \'MMMM\' de \'yyyy',
  'd \'de\' MMMM \'de\' y',
  'dd-MM-yyyy HH:mm:ss',
  'dd-MM-yyyy H:mm:ss',
  'dd-MM-yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MMMM\' de \'yyyy',
  'dd-MM-yy H:mm:ss',
  'dd-MM-yyyy HH:mm',
  'dd/MM/yy H:mm:ss',
  'd/M/yy HH:mm:ss',
  'dd-MM-yyyy H:mm',
  'd/M/yy H:mm:ss',
  'dd-MM-yy HH:mm',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'dd-MM-yy H:mm',
  'dd/MM/yy H:mm',
  'd/M/yy HH:mm',
  'd/M/yy H:mm',
  'h:mm:ss a z',
  'dd-MM-yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'dd-MM-yy',
  'dd/MM/yy',
  'H:mm:ss',
  'dd MMMM',
  'dd-MM-y',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];