formats["es-es"] = [
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'',
  'd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'',
  'dd/MM/yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'dd-MM-yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'dd.MM.yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'dd/MM/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd/MM/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm',
  'd/M/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm',
  'd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy',
  'HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'd\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE, d \'de\' MMMM \'de\' y',
  'dd/MM/yyyy HH\'H\'mm\'\'\'\'',
  'dd-MM-yy HH\'H\'mm\'\'\'\'',
  'dd.MM.yy HH\'H\'mm\'\'\'\'',
  'dd/MM/yy HH\'H\'mm\'\'\'\'',
  'd/MM/yy HH\'H\'mm\'\'\'\'',
  'd\' de \'MMMM\' de \'yyyy',
  'd/M/yy HH\'H\'mm\'\'\'\'',
  'd \'de\' MMMM \'de\' y',
  'dd/MM/yyyy HH:mm:ss',
  'dd/MM/yyyy H:mm:ss',
  'HH\'H\'mm\'\'\'\'',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MMMM\' de \'yyyy',
  'd/MM/yy HH:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yyyy HH:mm',
  'd/M/yy HH:mm:ss',
  'd/MM/yy H:mm:ss',
  'dd/MM/yyyy H:mm',
  'H:mm:ss (zzzz)',
  'd/M/yy H:mm:ss',
  'dd-MM-yy HH:mm',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'd/MM/yy HH:mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'd/M/yy HH:mm',
  'd/MM/yy H:mm',
  'd/M/yy H:mm',
  'dd/MM/yyyy',
  'H:mm:ss z',
  'HH:mm:ss',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'd/MM/yy',
  'dd MMMM',
  'd/M/yy',
  'HH:mm',
  'H:mm',
  'yyyy-MM-dd HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH\'H\'mm\'\'\'\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];