formats["es-pr"] = [
  'EEEE, dd\' de \'MMMM\' de \'yyyy hh:mm:ss a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy hh:mm a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE, dd\' de \'MMMM\' de \'yyyy',
  'EEEE, d \'de\' MMMM \'de\' y',
  'd \'de\' MMMM \'de\' y',
  'MM-dd-yyyy hh:mm:ss a',
  'dd/MM/yyyy hh:mm:ss a',
  'MM-dd-yyyy HH:mm:ss',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'MM-dd-yyyy hh:mm a',
  'dd/MM/yyyy hh:mm a',
  'dd/MM/yy HH:mm:ss',
  'MM-dd-yyyy HH:mm',
  'MMMM\' de \'yyyy',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'h:mm:ss a z',
  'MM-dd-yyyy',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'h:mm:ss a',
  'HH:mm:ss',
  'MM/dd/yy',
  'dd/MM/yy',
  'MM/dd/y',
  'dd MMMM',
  'hh:mm a',
  'h:mm a',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd'
];