formats["es-pa"] = [
  'EEEE, dd\' de \'MMMM\' de \'yyyy hh:mm:ss a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy h:mm:ss a',
  'EEEE d\' de \'MMMM\' de \'yyyy hh:mm:ss a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE d\' de \'MMMM\' de \'yyyy h:mm:ss a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy hh:mm a',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy h:mm a',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE d\' de \'MMMM\' de \'yyyy hh:mm a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy h:mm a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm',
  'd\' de \'MMMM\' de \'yyyy hh:mm:ss a',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm',
  'd\' de \'MMMM\' de \'yyyy h:mm:ss a',
  'd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'd\' de \'MMMM\' de \'yyyy hh:mm a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy h:mm a',
  'd\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE, d \'de\' MMMM \'de\' y',
  'd\' de \'MMMM\' de \'yyyy',
  'd \'de\' MMMM \'de\' y',
  'MM/dd/yyyy hh:mm:ss a',
  'MM/dd/yyyy h:mm:ss a',
  'MM/dd/yy hh:mm:ss a',
  'MM/dd/yyyy HH:mm:ss',
  'dd-MM-yy hh:mm:ss a',
  'dd/MM/yy hh:mm:ss a',
  'MM/dd/yy h:mm:ss a',
  'MM/dd/yyyy H:mm:ss',
  'MM/dd/yyyy hh:mm a',
  'dd-MM-yy h:mm:ss a',
  'dd/MM/yy h:mm:ss a',
  'MM/dd/yy HH:mm:ss',
  'MM/dd/yyyy h:mm a',
  'd/M/yy hh:mm:ss a',
  'dd-MM-yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MM/dd/yy H:mm:ss',
  'MM/dd/yy hh:mm a',
  'MM/dd/yyyy HH:mm',
  'MMMM\' de \'yyyy',
  'd/M/yy h:mm:ss a',
  'dd-MM-yy H:mm:ss',
  'dd-MM-yy hh:mm a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'MM/dd/yy h:mm a',
  'MM/dd/yyyy H:mm',
  'd/M/yy HH:mm:ss',
  'dd-MM-yy h:mm a',
  'dd/MM/yy h:mm a',
  'MM/dd/yy HH:mm',
  'd/M/yy H:mm:ss',
  'd/M/yy hh:mm a',
  'dd-MM-yy HH:mm',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'MM/dd/yy H:mm',
  'd/M/yy h:mm a',
  'dd-MM-yy H:mm',
  'dd/MM/yy H:mm',
  'd/M/yy HH:mm',
  'd/M/yy H:mm',
  'h:mm:ss a z',
  'MM/dd/yyyy',
  'hh:mm:ss a',
  'h:mm:ss a',
  'HH:mm:ss',
  'MM/dd/yy',
  'dd-MM-yy',
  'dd/MM/yy',
  'H:mm:ss',
  'MM/dd/y',
  'dd MMMM',
  'hh:mm a',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];