formats["et-ee"] = [
  'dd. MMMM yyyy\'. a.\' HH:mm:ss',
  'd. MMMM yyyy\'. a.\' HH:mm:ss',
  'dd. MMMM yyyy\'. a.\' H:mm:ss',
  'd. MMMM yyyy\'. a.\' H:mm:ss',
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy\'. a.\' HH:mm',
  'EEEE, d. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy\'. a.\' HH:mm',
  'dd. MMMM yyyy\'. a.\' H:mm',
  'd. MMMM yyyy\'. a.\' H:mm',
  'EEEE, d. MMMM yyyy HH:mm',
  'EEEE, d. MMMM yyyy H:mm',
  'dd. MMMM yyyy\'. a.\'',
  'd. MMMM yyyy\'. a.\'',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy',
  'd.MM.yyyy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'MMMM yyyy\'. a.\'',
  'd.MM.yyyy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'EEEE, d. MMMM y',
  'd.MM.yyyy HH:mm',
  'dd.MM.yyyy H:mm',
  'd.MM.yyyy H:mm',
  'dd.MM.yy HH:mm',
  'dd.MM.yy H:mm',
  'H:mm.ss zzzz',
  'dd.MM.yyyy',
  'H:mm.ss z',
  'd. MMMM y',
  'd.MM.yyyy',
  'HH:mm:ss',
  'd. MMM y',
  'dd.MM.yy',
  'H:mm.ss',
  'H:mm:ss',
  'd. MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];