formats["eu-es"] = [
  'EEEE, yyyy.\'eko\' MMMM\'k \'d HH:mm:ss',
  'EEEE, yyyy.\'eko\' MMMM\'k \'d HH:mm',
  'EEEE, yyyy.\'eko\' MMMM\'k \'d',
  'HH:mm:ss (zzzz)',
  'HH:mm:ss (z)',
  'HH:mm:ss',
  'MMMM dd',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'y(\'e\')\'ko\' MMMM d, EEEE',
  'y(\'e\')\'ko\' MMMM d',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yyyy.\'eko\' MMMM',
  'yyyy-MM-dd HH:mm',
  'yyyy/MM/dd HH:mm',
  'yyyy-MM-dd',
  'yyyy/MM/dd',
  'y MMM d',
  'y/MM/dd'
];