formats["fa-ir"] = [
  'EEEE, MMMM dd, yyyy hh:mm:ss a',
  'EEEE, MMMM dd, yyyy HH:mm:ss',
  'EEEE, MMMM dd, yyyy hh:mm a',
  'EEEE, MMMM dd, yyyy HH:mm',
  'MMMM dd, yyyy hh:mm:ss a',
  'MMMM dd, yyyy HH:mm:ss',
  'MM/dd/yyyy hh:mm:ss a',
  'MMMM dd, yyyy hh:mm a',
  'EEEE, MMMM dd, yyyy',
  'MM/dd/yy hh:mm:ss a',
  'MM/dd/yyyy HH:mm:ss',
  'MMMM dd, yyyy HH:mm',
  'MM/dd/yyyy hh:mm a',
  'MM/dd/yy HH:mm:ss',
  'MM/dd/yy hh:mm a',
  'MM/dd/yyyy HH:mm',
  'H:mm:ss (zzzz)',
  'MM/dd/yy HH:mm',
  'EEEE d MMMM y',
  'MMMM dd, yyyy',
  'H:mm:ss (z)',
  'MM/dd/yyyy',
  'MMMM, yyyy',
  'hh:mm:ss a',
  'HH:mm:ss',
  'MM/dd/yy',
  'd MMMM y',
  'H:mm:ss',
  'MMMM dd',
  'd MMM y',
  'hh:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'y/M/d'
];