formats["fi-fi"] = [
  'dd. MMMM\'ta \'yyyy HH:mm:ss',
  'd. MMMM\'ta \'yyyy HH:mm:ss',
  'dd. MMMM\'ta \'yyyy H:mm:ss',
  'd. MMMM\'ta \'yyyy H:mm:ss',
  'dd. MMMM\'ta \'yyyy HH:mm',
  'd. MMMM\'ta \'yyyy HH:mm',
  'dd. MMMM\'ta \'yyyy H:mm',
  'd. MMMM\'ta \'yyyy H:mm',
  'dd. MMMM\'ta \'yyyy',
  'dd.MM.yyyy HH:mm:ss',
  'd. MMMM\'ta \'yyyy',
  'dd.MM.yyyy H:mm:ss',
  'd.M.yyyy HH:mm:ss',
  'd.M.yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'd.M.yy HH:mm:ss',
  'dd.MM.yyyy H:mm',
  'cccc d. MMMM y',
  'd.M.yy H:mm:ss',
  'd.M.yyyy HH:mm',
  'd. MMMM\'ta\'',
  'd.M.yyyy H:mm',
  'H.mm.ss zzzz',
  'd.M.yy HH:mm',
  'd.M.yy H:mm',
  'dd.MM.yyyy',
  'H.mm.ss z',
  'MMMM yyyy',
  'd. MMMM y',
  'HH:mm:ss',
  'd.M.yyyy',
  'H.mm.ss',
  'H:mm:ss',
  'd.M.yy',
  'HH:mm',
  'd.M.y',
  'H.mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];