formats["fil-ph"] = [
  'dddd, MMMM d, yyyy h:mm:ss a',
  'dddd, MMMM d, yyyy HH:mm:ss',
  'MMMM d, yyyy h:mm:ss a',
  'MMM d, yyyy h:mm:ss a',
  'MMMM d, yyyy HH:mm:ss',
  'MMM d, yyyy HH:mm:ss',
  'M/d/yyyy h:mm:ss a',
  'dddd, MMMM d, yyyy',
  'M/d/yyyy HH:mm:ss',
  'EEEE, MMMM d, y',
  'h:mm:ss a zzzz',
  'MMMM d, yyyy',
  'MMM d, yyyy',
  'h:mm:ss a z',
  'MMMM d, y',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'M/d/yyyy',
  'MMM d, y',
  'MMMM dd',
  'M/d/yy',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];