formats["fo-fo"] = [
  'd. MMMM yyyy HH.mm.ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd-MM-yyyy HH.mm.ss',
  'dd-MM-yyyy HH:mm:ss',
  'd. MMMM yyyy HH.mm',
  'd. MMMM yyyy HH:mm',
  'dd-MM-yy HH.mm.ss',
  'dd-MM-yy HH:mm:ss',
  'dd-MM-yyyy HH.mm',
  'dd-MM-yyyy HH:mm',
  'EEEE dd MMMM y',
  'dd-MM-yy HH.mm',
  'dd-MM-yy HH:mm',
  'HH:mm:ss zzzz',
  'd. MMMM yyyy',
  'HH:mm:ss z',
  'dd-MM-yyyy',
  'MMMM yyyy',
  'HH.mm.ss',
  'HH:mm:ss',
  'd. MMM y',
  'dd-MM-yy',
  'd. MMMM',
  'dd-MM-y',
  'HH.mm',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH.mm.ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd HH.mm',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd'
];