formats["fr-be"] = [
  'EEEE d MMMM yyyy H\' h \'m\' min \'s\' s \'',
  'd MMMM yyyy H\' h \'m\' min \'s\' s \'',
  'dd/MM/yyyy H\' h \'m\' min \'s\' s \'',
  'd/MM/yyyy H\' h \'m\' min \'s\' s \'',
  'dd-MMM-yy H\' h \'m\' min \'s\' s \'',
  'EEEE d MMMM yyyy H\' h \'m\' min \'',
  'dd-MM-yy H\' h \'m\' min \'s\' s \'',
  'dd.MM.yy H\' h \'m\' min \'s\' s \'',
  'd/MM/yy H\' h \'m\' min \'s\' s \'',
  'H \'h\' mm \'min\' ss \'s\' zzzz',
  'd MMMM yyyy H\' h \'m\' min \'',
  'dd/MM/yyyy H\' h \'m\' min \'',
  'd/MM/yyyy H\' h \'m\' min \'',
  'dd-MMM-yy H\' h \'m\' min \'',
  'EEEE d MMMM yyyy H\' h \'mm',
  'dd-MM-yy H\' h \'m\' min \'',
  'dd.MM.yy H\' h \'m\' min \'',
  'H\' h \'m\' min \'s\' s \'',
  'd/MM/yy H\' h \'m\' min \'',
  'EEEE d MMMM yyyy HH:mm:ss',
  'EEEE d MMMM yyyy H:mm:ss',
  'EEEE d MMMM yyyy HH:mm',
  'd MMMM yyyy H\' h \'mm',
  'EEEE d MMMM yyyy H.mm',
  'EEEE d MMMM yyyy H:mm',
  'dd/MM/yyyy H\' h \'mm',
  'd MMMM yyyy HH:mm:ss',
  'd/MM/yyyy H\' h \'mm',
  'dd-MMM-yy H\' h \'mm',
  'd MMMM yyyy H:mm:ss',
  'dd-MM-yy H\' h \'mm',
  'dd.MM.yy H\' h \'mm',
  'dd/MM/yyyy HH:mm:ss',
  'H\' h \'m\' min \'',
  'd/MM/yy H\' h \'mm',
  'd/MM/yyyy HH:mm:ss',
  'dd-MMM-yy HH:mm:ss',
  'dd/MM/yyyy H:mm:ss',
  'd MMMM yyyy HH:mm',
  'd/MM/yyyy H:mm:ss',
  'dd-MM-yy HH:mm:ss',
  'dd-MMM-yy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'EEEE d MMMM yyyy',
  'd MMMM yyyy H.mm',
  'd MMMM yyyy H:mm',
  'd/MM/yy HH:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd/MM/yyyy HH:mm',
  'd/MM/yy H:mm:ss',
  'd/MM/yyyy HH:mm',
  'dd-MMM-yy HH:mm',
  'dd/MM/yyyy H.mm',
  'dd/MM/yyyy H:mm',
  'd/MM/yyyy H.mm',
  'd/MM/yyyy H:mm',
  'dd-MM-yy HH:mm',
  'dd-MMM-yy H.mm',
  'dd-MMM-yy H:mm',
  'dd.MM.yy HH:mm',
  'EEEE d MMMM y',
  'd/MM/yy HH:mm',
  'dd-MM-yy H.mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H.mm',
  'dd.MM.yy H:mm',
  'd/MM/yy H.mm',
  'd/MM/yy H:mm',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'H\' h \'mm',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'd/MM/yyyy',
  'dd-MMM-yy',
  'HH:mm:ss',
  'd MMMM y',
  'dd-MM-yy',
  'dd.MM.yy',
  'H:mm:ss',
  'd MMM y',
  'd/MM/yy',
  'd MMMM',
  'HH:mm',
  'H.mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd H\' h \'m\' min \'s\' s \'',
  'yy/MM/dd H\' h \'m\' min \'s\' s \'',
  'yyyy-MM-dd H\' h \'m\' min \'',
  'yy/MM/dd H\' h \'m\' min \'',
  'yyyy-MM-dd H\' h \'mm',
  'yy/MM/dd H\' h \'mm',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy/MM/dd HH:mm:ss',
  'yy/MM/dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H.mm',
  'yyyy-MM-dd H:mm',
  'yy/MM/dd HH:mm',
  'yy/MM/dd H.mm',
  'yy/MM/dd H:mm',
  'yyyy-MM-dd',
  'yy/MM/dd'
];