formats["fr-ca"] = [
  'd MMMM yyyy H\' h \'mm',
  'd MMM yyyy H\' h \'mm',
  'd MMMM yyyy HH:mm:ss',
  'd MMM yyyy HH:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'dd-MM-yy H\' h \'mm',
  'dd/MM/yy H\' h \'mm',
  'd MMM yyyy H:mm:ss',
  'd MMMM yyyy HH:mm',
  'dd-MM-yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'd MMM yyyy HH:mm',
  'd MMMM yyyy H:mm',
  'dd-MM-yy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'd MMM yyyy H:mm',
  'dd-MM-yy HH:mm',
  'dd/MM/yy HH:mm',
  'EEEE d MMMM y',
  'HH:mm:ss zzzz',
  'dd-MM-yy H:mm',
  'dd/MM/yy H:mm',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'H\' h \'mm',
  'MMMM, yyyy',
  'd MMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'dd-MM-yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'd MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd H\' h \'mm',
  'yy MM dd H\' h \'mm',
  'yy-MM-dd H\' h \'mm',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy MM dd HH:mm:ss',
  'yy-MM-dd HH:mm:ss',
  'yy MM dd H:mm:ss',
  'yy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yy MM dd HH:mm',
  'yy-MM-dd HH:mm',
  'yy MM dd H:mm',
  'yy-MM-dd H:mm',
  'yyyy-MM-dd',
  'yy MM dd',
  'yy-MM-dd'
];