formats["fr-cm"] = [
  'EEEE d MMMM yyyy HH:mm:ss',
  'd MMMM yyyy HH:mm:ss',
  'd MMM yyyy HH:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'EEEE d MMMM yyyy',
  'EEEE d MMMM y',
  'HH:mm:ss zzzz',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'd MMM yyyy',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'MMMM dd',
  'd MMM y',
  'dd/MM/y',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];