formats["fr-ch"] = [
  'EEEE, d. MMMM yyyy HH.mm\' h\'',
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss',
  'EEEE, d. MMMM yyyy HH:mm',
  'd. MMMM yyyy HH.mm\' h\'',
  'EEEE, d. MMMM yyyy H:mm',
  'dd.MM.yyyy HH.mm\' h\'',
  'd. MMMM yyyy HH:mm:ss',
  'dd. M. yy HH.mm\' h\'',
  'd MMM yy HH.mm\' h\'',
  'd. MMMM yyyy H:mm:ss',
  'dd.MM.yy HH.mm\' h\'',
  'HH.mm:ss \'h\' zzzz',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy',
  'd. MMMM yyyy HH:mm',
  'd.M.yy HH.mm\' h\'',
  'dd. M. yy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'd MMM yy HH:mm:ss',
  'd. MMMM yyyy H:mm',
  'dd. M. yy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'd MMM yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'd.M.yy HH:mm:ss',
  'dd. M. yy HH:mm',
  'dd.MM.yyyy H:mm',
  'EEEE, d MMMM y',
  'd MMM yy HH:mm',
  'd.M.yy H:mm:ss',
  'dd. M. yy H:mm',
  'dd.MM.yy HH:mm',
  'd MMM yy H:mm',
  'dd.MM.yy H:mm',
  'd. MMMM yyyy',
  'd.M.yy HH:mm',
  'HH.mm\' h\'',
  'd.M.yy H:mm',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'dd. M. yy',
  'HH:mm:ss',
  'd MMM yy',
  'd MMMM y',
  'dd.MM.yy',
  'H:mm:ss',
  'd MMM y',
  'd MMMM',
  'd.M.yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH.mm\' h\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];