formats["fr-lu"] = [
  'EEEE d MMMM yyyy HH\' h \'mm',
  'EEEE d MMMM yyyy HH:mm:ss',
  'EEEE d MMMM yyyy H:mm:ss',
  'd MMMM yyyy HH\' h \'mm',
  'EEEE d MMMM yyyy HH.mm',
  'EEEE d MMMM yyyy HH:mm',
  'dd/MM/yyyy HH\' h \'mm',
  'EEEE d MMMM yyyy H:mm',
  'd MMM yy HH\' h \'mm',
  'd MMMM yyyy HH:mm:ss',
  'dd-MM-yy HH\' h \'mm',
  'dd.MM.yy HH\' h \'mm',
  'dd/MM/yy HH\' h \'mm',
  'd MMMM yyyy H:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'dd/MM/yyyy H:mm:ss',
  'd MMM yy HH:mm:ss',
  'd MMMM yyyy HH.mm',
  'd MMMM yyyy HH:mm',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'EEEE d MMMM yyyy',
  'd MMM yy H:mm:ss',
  'd MMMM yyyy H:mm',
  'dd-MM-yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yyyy HH.mm',
  'dd/MM/yyyy HH:mm',
  'dd/MM/yyyy H:mm',
  'd MMM yy HH.mm',
  'd MMM yy HH:mm',
  'dd-MM-yy HH.mm',
  'dd-MM-yy HH:mm',
  'dd.MM.yy HH.mm',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH.mm',
  'dd/MM/yy HH:mm',
  'EEEE d MMMM y',
  'HH:mm:ss zzzz',
  'd MMM yy H:mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'HH\' h \'mm',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMM yy',
  'd MMMM y',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'dd/MM/y',
  'd MMMM',
  'HH.mm',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH\' h \'mm',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH.mm',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];