formats["gl-es"] = [
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'',
  'EEEE, dd\' de \'MMMM\' de \'yyyy hh:mm:ss a',
  'd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'\'\'\'',
  'dd/MM/yyyy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy hh:mm:ss a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, dd\' de \'MMMM\' de \'yyyy hh:mm a',
  'dd-MM-yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'dd.MM.yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'dd/MM/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd/MM/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE d\' de \'MMMM\' de \'yyyy hh:mm a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy HH:mm',
  'd/M/yy HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'EEEE, dd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy HH:mm',
  'd\' de \'MMMM\' de \'yyyy hh:mm:ss a',
  'EEEE d\' de \'MMMM\' de \'yyyy H:mm',
  'd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'd\' de \'MMMM\' de \'yyyy hh:mm a',
  'EEEE, dd\' de \'MMMM\' de \'yyyy',
  'HH\'H\'mm\'\'\'\'ss\'\'\'\'\'\'',
  'd\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE d\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy H:mm',
  'dd/MM/yyyy HH\'H\'mm\'\'\'\'',
  'dd-MM-yy HH\'H\'mm\'\'\'\'',
  'dd.MM.yy HH\'H\'mm\'\'\'\'',
  'dd/MM/yy HH\'H\'mm\'\'\'\'',
  'd/MM/yy HH\'H\'mm\'\'\'\'',
  'd\' de \'MMMM\' de \'yyyy',
  'd/M/yy HH\'H\'mm\'\'\'\'',
  'dd/MM/yyyy hh:mm:ss a',
  'dd-MM-yy hh:mm:ss a',
  'dd.MM.yy hh:mm:ss a',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'HH\'H\'mm\'\'\'\'',
  'd/M/yy hh:mm:ss a',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MMMM\' de \'yyyy',
  'd/MM/yy HH:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd-MM-yy hh:mm a',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yy hh:mm a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'd/M/yy HH:mm:ss',
  'd/MM/yy H:mm:ss',
  'd/MM/yy hh:mm a',
  'dd/MM/yyyy H:mm',
  'EEEE dd MMMM y',
  'd/M/yy H:mm:ss',
  'd/M/yy hh:mm a',
  'dd-MM-yy HH:mm',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'HH:mm:ss zzzz',
  'd/MM/yy HH:mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'd/M/yy HH:mm',
  'd/MM/yy H:mm',
  'd/M/yy H:mm',
  'HH:mm:ss z',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'dd MMMM y',
  'HH:mm:ss',
  'd MMM, y',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd/MM/yy',
  'dd MMMM',
  'hh:mm a',
  'd/M/yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];