formats["gsw-fr"] = [
  'dddd d MMMM yyyy HH:mm:ss',
  'dddd d MMMM yyyy H:mm:ss',
  'd MMMM yyyy HH:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'dd/MM/yyyy H:mm:ss',
  'd MMM yy HH:mm:ss',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'd MMM yy H:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'dddd d MMMM yyyy',
  'EEEE, d. MMMM y',
  'HH:mm:ss zzzz',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'd. MMMM y',
  'HH:mm:ss',
  'd MMM yy',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'MMMM dd',
  'dd.MM.y',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd'
];