formats["haw-us"] = [
  'EEEE, d MMMM yyyy h:mm:ss a',
  'EEEE, d MMMM yyyy HH:mm:ss',
  'd MMMM yyyy h:mm:ss a',
  'd MMM yyyy h:mm:ss a',
  'd MMMM yyyy HH:mm:ss',
  'd MMM yyyy HH:mm:ss',
  'd/M/yyyy h:mm:ss a',
  'EEEE, d MMMM yyyy',
  'd/M/yyyy HH:mm:ss',
  'EEEE, d MMMM y',
  'h:mm:ss a zzzz',
  'd MMMM yyyy',
  'h:mm:ss a z',
  'd MMM yyyy',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'd/M/yyyy',
  'MMMM dd',
  'd MMM y',
  'd/M/yy',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];