formats["he-il"] = [
  'EEEE dd בMMMM yyyy hh:mm:ss a',
  'EEE dd בMMMM yyyy hh:mm:ss a',
  'EEEE dd MMMM yyyy hh:mm:ss a',
  'EEEE dd בMMMM yyyy HH:mm:ss',
  'EEE dd בMMMM yyyy HH:mm:ss',
  'EEEE dd MMMM yyyy HH:mm:ss',
  'EEEE dd בMMMM yyyy hh:mm a',
  'EEE dd בMMMM yyyy hh:mm a',
  'EEEE dd MMMM yyyy hh:mm a',
  'EEEE dd בMMMM yyyy HH:mm',
  'dd בMMMM yyyy hh:mm:ss a',
  'EEE dd בMMMM yyyy HH:mm',
  'EEEE dd MMMM yyyy HH:mm',
  'dd MMMM yyyy hh:mm:ss a',
  'dd-MMMM-yyyy hh:mm:ss a',
  'dd/MMMM/yyyy hh:mm:ss a',
  'dd בMMMM yyyy HH:mm:ss',
  'dd MMMM yyyy HH:mm:ss',
  'dd בMMMM yyyy hh:mm a',
  'dd-MM-yyyy hh:mm:ss a',
  'dd-MMMM-yyyy HH:mm:ss',
  'dd/MM/yyyy hh:mm:ss a',
  'dd/MMMM/yyyy HH:mm:ss',
  'dd MMM yy hh:mm:ss a',
  'dd MMMM yyyy hh:mm a',
  'dd-MMMM-yyyy hh:mm a',
  'dd/MMMM/yyyy hh:mm a',
  'dd בMMMM yyyy HH:mm',
  'dd-MM-yy hh:mm:ss a',
  'dd-MM-yyyy HH:mm:ss',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'EEEE dd בMMMM yyyy',
  'dd MMM yy HH:mm:ss',
  'dd MMMM yyyy HH:mm',
  'dd-MM-yyyy hh:mm a',
  'dd-MMMM-yyyy HH:mm',
  'dd/MM/yyyy hh:mm a',
  'dd/MMMM/yyyy HH:mm',
  'EEE dd בMMMM yyyy',
  'EEEE dd MMMM yyyy',
  'dd MMM yy hh:mm a',
  'dd-MM-yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'EEEE, d בMMMM y',
  'dd-MM-yy hh:mm a',
  'dd-MM-yyyy HH:mm',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'dd MMM yy HH:mm',
  'dd-MM-yy HH:mm',
  'dd/MM/yy HH:mm',
  'dd בMMMM yyyy',
  'H:mm:ss zzzz',
  'dd MMMM yyyy',
  'dd-MMMM-yyyy',
  'dd/MMMM/yyyy',
  'd בMMMM y',
  'dd-MM-yyyy',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'H:mm:ss z',
  'MMMM yyyy',
  'd בMMM y',
  'dd MMM yy',
  'HH:mm:ss',
  'dd-MM-yy',
  'dd/MM/yy',
  'H:mm:ss',
  'dd MMMM',
  'hh:mm a',
  'HH:mm',
  'd.M.y',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd'
];