formats["hu-hu"] = [
  'H:mm:ss zzzz',
  'H:mm:ss z',
  'h:mm:ss a',
  'HH:mm:ss',
  'H:mm:ss',
  'MMMM d.',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy. MM. dd. h:mm:ss a',
  'yyyy. MMMM d. h:mm:ss a',
  'yyyy. MM. dd. HH:mm:ss',
  'yyyy. MMMM d. HH:mm:ss',
  'yyyy. MM. dd. H:mm:ss',
  'yyyy. MMMM d. H:mm:ss',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy. MM. dd. h:mm a',
  'yyyy. MMMM d. h:mm a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy. MM. dd. HH:mm',
  'yyyy. MMMM d. HH:mm',
  'yy-MM-dd h:mm:ss a',
  'yyyy-MM-dd H:mm:ss',
  'yyyy. MM. dd. H:mm',
  'yyyy. MMMM d. H:mm',
  'yy-MM-dd HH:mm:ss',
  'yyyy-MM-dd h:mm a',
  'y. MMMM d., EEEE',
  'yy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yy-MM-dd h:mm a',
  'yyyy-MM-dd H:mm',
  'yy-MM-dd HH:mm',
  'yy-MM-dd H:mm',
  'yyyy. MM. dd.',
  'yyyy. MMMM d.',
  'y. MM. dd.',
  'y. MMMM d.',
  'yyyy-MM-dd',
  'yyyy. MMMM',
  'y. MMM d.',
  'yy-MM-dd'
];