formats["hy-am"] = [
  'EEEE, dd MMMM yyyy HH:mm:ss',
  'EEE, dd-MMMM-yyyy HH:mm:ss',
  'EEEE, d MMMM yyyy HH:mm:ss',
  'EEEE, dd MMMM yyyy H:mm:ss',
  'EEE, d-MMMM-yyyy HH:mm:ss',
  'EEE, dd-MMMM-yyyy H:mm:ss',
  'EEEE, d MMMM yyyy H:mm:ss',
  'EEE, d-MMMM-yyyy H:mm:ss',
  'EEEE, dd MMMM yyyy HH:mm',
  'EEE, dd-MMMM-yyyy HH:mm',
  'EEEE, d MMMM yyyy HH:mm',
  'EEEE, dd MMMM yyyy H:mm',
  'EEE, d-MMMM-yyyy HH:mm',
  'EEE, dd-MMMM-yyyy H:mm',
  'EEEE, d MMMM yyyy H:mm',
  'EEE, d-MMMM-yyyy H:mm',
  'd MMMM, yyyy HH:mm:ss',
  'dd MMMM yyyy HH:mm:ss',
  'd MMMM, yyyy H:mm:ss',
  'dd MMMM yyyy H:mm:ss',
  'dd-MMM-yyyy HH:mm:ss',
  'dd/MMM/yyyy HH:mm:ss',
  'd-MMM-yyyy HH:mm:ss',
  'd/MMM/yyyy HH:mm:ss',
  'dd-MMM-yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'dd/MMM/yyyy H:mm:ss',
  'EEEE, dd MMMM yyyy',
  'd MMMM, yyyy HH:mm',
  'd-MMM-yyyy H:mm:ss',
  'd/MM/yyyy HH:mm:ss',
  'd/MMM/yyyy H:mm:ss',
  'dd MMMM yyyy HH:mm',
  'dd.MM.yyyy H:mm:ss',
  'dd/MM/yyyy H:mm:ss',
  'EEE, dd-MMMM-yyyy',
  'EEEE, d MMMM yyyy',
  'd MMMM, yyyy H:mm',
  'd/MM/yyyy H:mm:ss',
  'dd MMMM yyyy H:mm',
  'dd-MMM-yyyy HH:mm',
  'dd.MM.yy HH:mm:ss',
  'dd/MMM/yyyy HH:mm',
  'EEE, d-MMMM-yyyy',
  'd-MMM-yyyy HH:mm',
  'd/MMM/yyyy HH:mm',
  'dd-MMM-yyyy H:mm',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd/MM/yyyy HH:mm',
  'dd/MMM/yyyy H:mm',
  'd-MMM-yyyy H:mm',
  'd/MM/yyyy HH:mm',
  'd/MMM/yyyy H:mm',
  'dd.MM.yyyy H:mm',
  'dd/MM/yyyy H:mm',
  'd/MM/yyyy H:mm',
  'dd.MM.yy HH:mm',
  'H:mm:ss, zzzz',
  'dd MMMM, yթ.',
  'dd.MM.yy H:mm',
  'd MMMM, yyyy',
  'dd MMM, yթ.',
  'dd MMMM yyyy',
  'dd-MMM-yyyy',
  'dd/MMM/yyyy',
  'H:mm:ss, z',
  'MMMM, yyyy',
  'd-MMM-yyyy',
  'd/MMM/yyyy',
  'dd.MM.yyyy',
  'dd/MM/yyyy',
  'd/MM/yyyy',
  'HH:mm:ss',
  'dd.MM.yy',
  'H:mm:ss',
  'd MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yթ. MMMM d, EEEE',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];