formats["id-id"] = [
  'dd MMMM yyyy HH:mm:ss',
  'dd MMMM yyyy H:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'dd MMMM yyyy HH:mm',
  'dd/MM/yyyy H:mm:ss',
  'dd MMMM yyyy H:mm',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yyyy HH:mm',
  'EEEE, dd MMMM y',
  'dd/MM/yyyy H:mm',
  'dd/MM/yy HH:mm',
  'HH.mm.ss zzzz',
  'dd/MM/yy H:mm',
  'dd MMMM yyyy',
  'HH.mm.ss z',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'HH.mm.ss',
  'HH:mm:ss',
  'd MMMM y',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'dd MMMM',
  'HH.mm',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];