formats["ii-cn"] = [
  'dddd, yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\' a h:mm:ss',
  'dddd, yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\' HH:mm:ss',
  'dddd, yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\' H:mm:ss',
  'dddd, yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\'',
  'dddd, yyyyꈎ MMM dꑍ a h:mm:ss',
  'dddd, yyyyꈎ MMM dꑍ HH:mm:ss',
  'dddd, yyyyꈎ MMM dꑍ H:mm:ss',
  'dddd, yyyyꈎ MMM dꑍ',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'a h:mm:ss',
  'HH:mm:ss',
  'H:mm:ss',
  'MMMM dd',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\', dddd a h:mm:ss',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\', dddd HH:mm:ss',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\', dddd H:mm:ss',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\' a h:mm:ss',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\' HH:mm:ss',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\' H:mm:ss',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\', dddd',
  'yyyy\'ꈎ\' M\'ꆪ\' d\'ꑍ\'',
  'yyyyꈎ MMM dꑍ a h:mm:ss',
  'yyyyꈎ MMM dꑍ HH:mm:ss',
  'yyyy-MM-dd a h:mm:ss',
  'yyyy.MM.dd a h:mm:ss',
  'yyyy/MM/dd a h:mm:ss',
  'yyyyꈎ MMM dꑍ H:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy.MM.dd HH:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yyyy-M-d a h:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy.M.d a h:mm:ss',
  'yyyy.MM.dd H:mm:ss',
  'yyyy/M/d a h:mm:ss',
  'yyyy/MM/dd H:mm:ss',
  'yyyy-M-d HH:mm:ss',
  'yyyy.M.d HH:mm:ss',
  'yyyy/M/d HH:mm:ss',
  'yyyy-M-d H:mm:ss',
  'yyyy.M.d H:mm:ss',
  'yyyy/M/d H:mm:ss',
  'yyyy\'ꈎ\' M\'ꆪ\'',
  'y MMMM d, EEEE',
  'yyyyꈎ MMM dꑍ',
  'yyyy-MM-dd',
  'yyyy.MM.dd',
  'yyyy/MM/dd',
  'y MMMM d',
  'yyyy-M-d',
  'yyyy.M.d',
  'yyyy/M/d',
  'y MMM d',
  'y-MM-dd',
  'yyyy.M'
];