formats["is-is"] = [
  'd. M. \'\'\'\'yy. HH:mm:ss',
  'd. M. \'\'\'\'yy. H:mm:ss',
  'd. M. \'\'\'\'yy. HH:mm',
  'd. M. \'\'\'\'yy. H:mm',
  'dd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy H:mm:ss',
  'd. M. yyyy. HH:mm:ss',
  'd. MMMM yyyy H:mm:ss',
  'd. M. yyyy. H:mm:ss',
  'dd. MMMM yyyy HH:mm',
  'd. MMMM yyyy HH:mm',
  'dd. MMMM yyyy H:mm',
  'd. M. \'\'\'\'yy.',
  'd. M. yyyy. HH:mm',
  'd. MMMM yyyy H:mm',
  'd.M.yyyy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'd. M. yyyy. H:mm',
  'd.M.yyyy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'EEEE, d. MMMM y',
  'd.M.yyyy HH:mm',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'd.M.yyyy H:mm',
  'dd. MMMM yyyy',
  'dd.MM.yy H:mm',
  'd. MMMM yyyy',
  'd. M. yyyy.',
  'HH:mm:ss z',
  'MMMM yyyy',
  'd. MMMM y',
  'HH:mm:ss',
  'd. MMM y',
  'd.M.yyyy',
  'dd.MM.yy',
  'H:mm:ss',
  'd. MMMM',
  'HH:mm',
  'd.M.y',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy MM dd HH:mm:ss',
  'yy MM dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yy MM dd HH:mm',
  'yy MM dd H:mm',
  'yyyy-MM-dd',
  'yy MM dd'
];