formats["it-ch"] = [
  'EEEE, d. MMMM yyyy H.mm\' h\'',
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss',
  'EEEE, d. MMMM yyyy HH:mm',
  'EEEE, d. MMMM yyyy H:mm',
  'd MMMM yyyy H.mm\' h\'',
  'dd. MM. yy H.mm\' h\'',
  'dd.MM.yyyy H.mm\' h\'',
  'd MMMM yyyy HH:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'd-MMM-yy H.mm\' h\'',
  'dd. MM. yy HH:mm:ss',
  'dd.MM.yy H.mm\' h\'',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy',
  'dd. MM. yy H:mm:ss',
  'dd.M.yy H.mm\' h\'',
  'dd.MM.yyyy H:mm:ss',
  'd MMMM yyyy HH:mm',
  'd-MMM-yy HH:mm:ss',
  'd/M/yy H.mm\' h\'',
  'dd.MM.yy HH:mm:ss',
  'd MMMM yyyy H:mm',
  'd-MMM-yy H:mm:ss',
  'dd. MM. yy HH:mm',
  'dd.M.yy HH:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'd/M/yy HH:mm:ss',
  'dd. MM. yy H:mm',
  'dd.M.yy H:mm:ss',
  'dd.MM.yyyy H:mm',
  'EEEE, d MMMM y',
  'd-MMM-yy HH:mm',
  'd/M/yy H:mm:ss',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'd-MMM-yy H:mm',
  'dd.M.yy HH:mm',
  'dd.MM.yy H:mm',
  'd/M/yy HH:mm',
  'dd.M.yy H:mm',
  'd MMMM yyyy',
  'd/M/yy H:mm',
  'H.mm\' h\'',
  'HH:mm:ss z',
  'dd. MM. yy',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'd-MMM-yy',
  'dd.MM.yy',
  'H:mm:ss',
  'd-MMM-y',
  'd. MMMM',
  'dd.M.yy',
  'd/M/yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd H.mm\' h\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];