formats["ja-jp"] = [
  'H時mm分ss秒 zzzz',
  'M\'月\'d\'日\'',
  'a hh:mm:ss',
  'H:mm:ss z',
  'a h:mm:ss',
  'HH:mm:ss',
  'H:mm:ss',
  'a hh:mm',
  'a h:mm',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd a hh:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd a h:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd HH:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' dddd a hh:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd H:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd a hh:mm',
  'yyyy\'年\'M\'月\'d\'日\' dddd a h:mm:ss',
  'yyyy/MM/dd\' (\'ddd\')\' a hh:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd a h:mm',
  'yyyy\'年\'M\'月\'d\'日\' dddd HH:mm:ss',
  'yyyy/MM/dd\' (\'ddd\')\' a h:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' a hh:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd HH:mm',
  'yyyy\'年\'M\'月\'d\'日\' dddd H:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' dddd a hh:mm',
  'yy/MM/dd\' (\'ddd\')\' a hh:mm:ss',
  'yyyy/MM/dd\' (\'ddd\')\' HH:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' a h:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd H:mm',
  'yyyy\'年\'M\'月\'d\'日\' dddd a h:mm',
  'yy/MM/dd\' (\'ddd\')\' a h:mm:ss',
  'yyyy/MM/dd\' (\'ddd\')\' H:mm:ss',
  'yyyy/MM/dd\' (\'ddd\')\' a hh:mm',
  'yyyy\'年\'MM\'月\'dd\'日\' HH:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' a hh:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' dddd HH:mm',
  'yy/M/d\' (\'ddd\')\' a hh:mm:ss',
  'yy/MM/dd\' (\'ddd\')\' HH:mm:ss',
  'yyyy/MM/dd\' (\'ddd\')\' a h:mm',
  'yyyy\'年\'MM\'月\'dd\'日\' H:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' a hh:mm',
  'yyyy\'年\'M\'月\'d\'日\' a h:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' dddd H:mm',
  'yy/M/d\' (\'ddd\')\' a h:mm:ss',
  'yy/MM/dd\' (\'ddd\')\' H:mm:ss',
  'yy/MM/dd\' (\'ddd\')\' a hh:mm',
  'yyyy/MM/dd\' (\'ddd\')\' HH:mm',
  'yyyy\'年\'MM\'月\'dd\'日\' a h:mm',
  'yyyy\'年\'M\'月\'d\'日\' HH:mm:ss',
  'yy/M/d\' (\'ddd\')\' HH:mm:ss',
  'yy/MM/dd\' (\'ddd\')\' a h:mm',
  'yyyy/MM/dd\' (\'ddd\')\' H:mm',
  'yyyy\'年\'MM\'月\'dd\'日\' HH:mm',
  'yyyy\'年\'M\'月\'d\'日\' H:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' a hh:mm',
  'yy/M/d\' (\'ddd\')\' H:mm:ss',
  'yy/M/d\' (\'ddd\')\' a hh:mm',
  'yy/MM/dd\' (\'ddd\')\' HH:mm',
  'yyyy\'年\'MM\'月\'dd\'日\' H:mm',
  'yyyy\'年\'MM\'月\'dd\'日\' dddd',
  'yyyy\'年\'M\'月\'d\'日\' a h:mm',
  'yy/M/d\' (\'ddd\')\' a h:mm',
  'yy/MM/dd\' (\'ddd\')\' H:mm',
  'yyyy\'年\'M\'月\'d\'日\' HH:mm',
  'yy/M/d\' (\'ddd\')\' HH:mm',
  'yyyy\'年\'M\'月\'d\'日\' H:mm',
  'yyyy\'年\'M\'月\'d\'日\' dddd',
  'yy/M/d\' (\'ddd\')\' H:mm',
  'yyyy/MM/dd\' (\'ddd\')\'',
  'yyyy\'年\'MM\'月\'dd\'日\'',
  'yy/MM/dd\' (\'ddd\')\'',
  'yyyy-MM-dd a hh:mm:ss',
  'yyyy/MM/dd a hh:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\'',
  'yy/M/d\' (\'ddd\')\'',
  'yyyy-MM-dd a h:mm:ss',
  'yyyy/MM/dd a h:mm:ss',
  'yy/MM/dd a hh:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy/M/d a hh:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yy/MM/dd a h:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd a hh:mm',
  'yyyy/M/d a h:mm:ss',
  'yyyy/MM/dd H:mm:ss',
  'yyyy/MM/dd a hh:mm',
  'yy/M/d a hh:mm:ss',
  'yy/MM/dd HH:mm:ss',
  'yyyy-MM-dd a h:mm',
  'yyyy/M/d HH:mm:ss',
  'yyyy/MM/dd a h:mm',
  'yy/M/d a h:mm:ss',
  'yy/MM/dd H:mm:ss',
  'yy/MM/dd a hh:mm',
  'yyyy-MM-dd HH:mm',
  'yyyy/M/d H:mm:ss',
  'yyyy/M/d a hh:mm',
  'yyyy/MM/dd HH:mm',
  'y年M月d日EEEE',
  'yy/M/d HH:mm:ss',
  'yy/MM/dd a h:mm',
  'yyyy-MM-dd H:mm',
  'yyyy/M/d a h:mm',
  'yyyy/MM/dd H:mm',
  'yyyy\'年\'M\'月\'',
  'yy/M/d H:mm:ss',
  'yy/M/d a hh:mm',
  'yy/MM/dd HH:mm',
  'yyyy/M/d HH:mm',
  'yy/M/d a h:mm',
  'yy/MM/dd H:mm',
  'yyyy/M/d H:mm',
  'yy/M/d HH:mm',
  'y年M月d日',
  'yy/M/d H:mm',
  'yyyy-MM-dd',
  'yyyy/MM/dd',
  'yy/MM/dd',
  'yyyy/M/d',
  'y/MM/dd',
  'yy/M/d'
];