formats["ka-ge"] = [
  'dd.MM.yyyy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'EEEE, dd MMMM, y',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd/MM/yy H:mm:ss',
  'd.M.yy HH:mm:ss',
  'dd.MM.yyyy H:mm',
  'd.M.yy H:mm:ss',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'HH:mm:ss zzzz',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'd.M.yy HH:mm',
  'd.M.yy H:mm',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'd MMMM, y',
  'HH:mm:ss',
  'd MMM, y',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd.M.yy',
  'HH:mm',
  'dd MM',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy \'წლის\' dd MM, EEEE HH:mm:ss',
  'yyyy \'წლის\' dd MM, EEEE H:mm:ss',
  'yyyy \'წლის\' dd MM, EEEE HH:mm',
  'yyyy \'წლის\' dd MM, EEEE H:mm',
  'yyyy \'წლის\' dd MM, EEEE',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];