formats["kl-gl"] = [
  'MMMM d\'.-at, \'yyyy HH:mm:ss',
  'MMMM d\'.-at, \'yyyy H:mm:ss',
  'dd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy H:mm:ss',
  'MMMM d\'.-at, \'yyyy',
  'd. MMMM yyyy H:mm:ss',
  'dd-MM-yyyy HH:mm:ss',
  'dd-MM-yyyy H:mm:ss',
  'dd-MM-yy HH:mm:ss',
  'dd-MM-yy H:mm:ss',
  'EEEE dd MMMM y',
  'h:mm:ss a zzzz',
  'dd. MMMM yyyy',
  'd. MMMM yyyy',
  'h:mm:ss a z',
  'dd-MM-yyyy',
  'MMM dd, y',
  'MMMM yyyy',
  'dd MMMM y',
  'h:mm:ss a',
  'HH:mm:ss',
  'dd-MM-yy',
  'H:mm:ss',
  'MMMM dd',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy MM dd HH:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy MM dd H:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy MM dd',
  'yyyy-MM-dd',
  'y-MM-dd'
];