formats["km-kh"] = [
  '\'ខែ\' MM \'ឆ្នាំ\' yyyy',
  'ddd d MMMM yyyy HH:mm:ss',
  'd MMMM yyyy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'ddd d MMMM yyyy',
  'h:mm:ss a zzzz',
  'EEEE d MMMM y',
  'd MMMM yyyy',
  'h:mm:ss a z',
  'h:mm:ss a',
  'HH:mm:ss',
  'd MMMM y',
  'dd/MM/yy',
  'MMMM dd',
  'd MMM y',
  'd/M/yy',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd'
];