formats["ko-kr"] = [
  'a h시 m분 s초 zzzz',
  'a h시 m분 s초 z',
  'M\'월\' d\'일\'',
  'a hh:mm:ss',
  'a h:mm:ss',
  'HH:mm:ss',
  'H:mm:ss',
  'a hh:mm',
  'a h:mm',
  'HH:mm',
  'H:mm',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE a hh:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE a h:mm:ss',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE HH:mm:ss',
  'yyyy\'년\' M\'월\' d\'일\' EEEE a hh:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE H:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE a hh:mm',
  'yyyy\'년\' M\'월\' d\'일\' EEEE a h:mm:ss',
  'yy\'년\' M\'월\' d\'일\' EEEE a hh:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE a h:mm',
  'yyyy\'년\' M\'월\' d\'일\' EEEE HH:mm:ss',
  'yy\'년\' M\'월\' d\'일\' EEEE a h:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE HH:mm',
  'yyyy\'년\' MM\'월\' dd\'일\' a hh:mm:ss',
  'yyyy\'년\' M\'월\' d\'일\' EEEE H:mm:ss',
  'yyyy\'년\' M\'월\' d\'일\' EEEE a hh:mm',
  'yy\'년\' M\'월\' d\'일\' EEEE HH:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE H:mm',
  'yyyy\'년\' MM\'월\' dd\'일\' a h:mm:ss',
  'yyyy\'년\' M\'월\' d\'일\' EEEE a h:mm',
  'yy\'년\' M\'월\' d\'일\' EEEE H:mm:ss',
  'yy\'년\' M\'월\' d\'일\' EEEE a hh:mm',
  'yyyy\'년\' MM\'월\' dd\'일\' HH:mm:ss',
  'yyyy\'년\' M\'월\' d\'일\' EEEE HH:mm',
  'yyyy\'년\' M\'월\' d\'일\' a hh:mm:ss',
  'yy\'년\' M\'월\' d\'일\' EEEE a h:mm',
  'yyyy\'년\' MM\'월\' dd\'일\' H:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' a hh:mm',
  'yyyy\'년\' M\'월\' d\'일\' EEEE H:mm',
  'yyyy\'년\' M\'월\' d\'일\' a h:mm:ss',
  'yy\'년\' M\'월\' d\'일\' EEEE HH:mm',
  'yy\'년\' M\'월\' d\'일\' a hh:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' a h:mm',
  'yyyy\'년\' M\'월\' d\'일\' HH:mm:ss',
  'yy\'년\' M\'월\' d\'일\' EEEE H:mm',
  'yy\'년\' M\'월\' d\'일\' a h:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' HH:mm',
  'yyyy\'년\' M\'월\' d\'일\' H:mm:ss',
  'yyyy\'년\' M\'월\' d\'일\' a hh:mm',
  'yy\'년\' M\'월\' d\'일\' HH:mm:ss',
  'yyyy\'년\' MM\'월\' dd\'일\' EEEE',
  'yyyy\'년\' MM\'월\' dd\'일\' H:mm',
  'yyyy\'년\' M\'월\' d\'일\' a h:mm',
  'yy\'년\' M\'월\' d\'일\' H:mm:ss',
  'yy\'년\' M\'월\' d\'일\' a hh:mm',
  'yyyy\'년\' M\'월\' d\'일\' HH:mm',
  'yy\'년\' M\'월\' d\'일\' a h:mm',
  'yyyy\'년\' M\'월\' d\'일\' EEEE',
  'yyyy\'년\' M\'월\' d\'일\' H:mm',
  'yy\'년\' M\'월\' d\'일\' HH:mm',
  'yy\'년\' M\'월\' d\'일\' EEEE',
  'yy\'년\' M\'월\' d\'일\' H:mm',
  'yyyy\'년\' MM\'월\' dd\'일\'',
  'yyyy\'년\' M\'월\' d\'일\'',
  'yy\'년\' M\'월\' d\'일\'',
  'yyyy-MM-dd a hh:mm:ss',
  'yyyy-MM-dd a h:mm:ss',
  'yy-MM-dd a hh:mm:ss',
  'yyyy-M-d a hh:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'y년 M월 d일 EEEE',
  'yy-MM-dd a h:mm:ss',
  'yyyy-M-d a h:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd a hh:mm',
  'yy-M-d a hh:mm:ss',
  'yy-MM-dd HH:mm:ss',
  'yyyy-M-d HH:mm:ss',
  'yyyy-MM-dd a h:mm',
  'yy-M-d a h:mm:ss',
  'yy-MM-dd H:mm:ss',
  'yy-MM-dd a hh:mm',
  'yyyy-M-d H:mm:ss',
  'yyyy-M-d a hh:mm',
  'yyyy-MM-dd HH:mm',
  'yyyy\'년\' M\'월\'',
  'yy-M-d HH:mm:ss',
  'yy-MM-dd a h:mm',
  'yyyy-M-d a h:mm',
  'yyyy-MM-dd H:mm',
  'yy-M-d H:mm:ss',
  'yy-M-d a hh:mm',
  'yy-MM-dd HH:mm',
  'yyyy-M-d HH:mm',
  'y년 M월 d일',
  'yy-M-d a h:mm',
  'yy-MM-dd H:mm',
  'yyyy-M-d H:mm',
  'yy-M-d HH:mm',
  'yy-M-d H:mm',
  'yyyy-MM-dd',
  'yy. M. d.',
  'y. M. d.',
  'yy-MM-dd',
  'yyyy-M-d',
  'yy-M-d'
];