formats["lb-lu"] = [
  'EEEE,\' den \'dd. MMMM yyyy HH:mm:ss\' Auer\'',
  'EEEE,\' den \'d. MMMM yyyy HH:mm:ss\' Auer\'',
  'EEEE,\' den \'dd. MMMM yyyy H:mm:ss\' Auer\'',
  'EEEE,\' den \'d. MMMM yyyy H:mm:ss\' Auer\'',
  'EEEE, dd. MMMM yyyy HH:mm:ss\' Auer\'',
  'EEEE, d. MMMM yyyy HH:mm:ss\' Auer\'',
  'EEEE, dd. MMMM yyyy H:mm:ss\' Auer\'',
  'EEEE,\' den \'dd. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss\' Auer\'',
  'EEEE,\' den \'d. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH:mm:ss\' Auer\'',
  'dd. MMMMyyyy HH:mm:ss\' Auer\'',
  'd. MMMM yyyy H:mm:ss\' Auer\'',
  'dd. MMMMyyyy H:mm:ss\' Auer\'',
  'EEEE, dd. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'EEEE,\' den \'dd. MMMM yyyy',
  'EEEE,\' den \'d. MMMM yyyy',
  'dd-MM-yy HH:mm:ss\' Auer\'',
  'dd.MM.yy HH:mm:ss\' Auer\'',
  'dd/MM/yy HH:mm:ss\' Auer\'',
  'dd-MM-yy H:mm:ss\' Auer\'',
  'dd.MM.yy H:mm:ss\' Auer\'',
  'dd/MM/yy H:mm:ss\' Auer\'',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMMyyyy HH:mm:ss',
  'EEEE, dd. MMMM yyyy',
  'EEEE, d. MMMM yyyy',
  'HH:mm:ss\' Auer\'',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'H:mm:ss\' Auer\'',
  'EEEE, d. MMMM y',
  'HH:mm:ss zzzz',
  'd. MMMM yyyy',
  'dd. MMMMyyyy',
  'HH:mm:ss z',
  'MMMM yyyy',
  'd. MMMM y',
  'HH:mm:ss',
  'd. MMM y',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'MMMM dd',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];