formats["lo-la"] = [
  'H ໂມງ m ນາທີ ss ວິນາທີ zzzz',
  'H ໂມງ m ນາທີ ss ວິນາທີ z',
  'EEEE ທີ d MMMM G yyyy HH:mm:ss',
  'EEEE ທີ d MMMM G yyyy H:mm:ss',
  'EEEE ທີ d MMMM G y',
  'EEEE ທີ d MMMM G yyyy',
  'd MMMM yyyy HH:mm:ss',
  'd MMM yyyy HH:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'd MMM yyyy H:mm:ss',
  'd/M/yyyy HH:mm:ss',
  'd/M/yyyy H:mm:ss',
  'd MMMM yyyy',
  'd MMM yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'd/M/yyyy',
  'H:mm:ss',
  'MMMM dd',
  'd MMM y',
  'd/M/y',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];