formats["lv-lv"] = [
  'EEEE, yyyy\'. gada \'d. MMMM HH:mm:ss',
  'EEEE, yyyy\'. gada \'d. MMMM H:mm:ss',
  'EEEE, yyyy\'. gada \'d. MMMM HH:mm',
  'EEEE, yyyy\'. gada \'d. MMMM H:mm',
  'EEEE, yyyy\'. gada \'d. MMMM',
  'EEEE, y. \'gada\' d. MMMM',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'HH:mm:ss',
  'dd.MM.yy',
  'H:mm:ss',
  'd. MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy.MM.dd. HH:mm:ss',
  'y. \'gada\' d. MMMM',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy.MM.dd. H:mm:ss',
  'y. \'gada\' d. MMM',
  'yy.MM.dd. HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy.MM.dd. H:mm:ss',
  'yyyy.MM.dd. HH:mm',
  'yyyy-MM-dd HH:mm',
  'yyyy.MM.dd. H:mm',
  'yy.MM.dd. HH:mm',
  'yyyy-MM-dd H:mm',
  'yy.MM.dd. H:mm',
  'yyyy.MM.dd.',
  'yyyy-MM-dd',
  'yyyy. MMMM',
  'yy.MM.dd.'
];