formats["mk-mk"] = [
  'EEEE, dd MMMM yyyy HH:mm:ss',
  'EEEE, dd MMMM yyyy HH:mm',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, dd MMMM yyyy',
  'dd.MM.yy HH:mm:ss',
  'dd.MM.yyyy HH:mm',
  'EEEE, dd MMMM y',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'dd MMMM y',
  'HH:mm:ss',
  'dd.MM.yy',
  'dd MMMM',
  'dd.M.yy',
  'dd.M.y',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd'
];