formats["mt-mt"] = [
  'EEEE, d \'ta\'’ MMMM yyyy HH:mm:ss',
  'd \'ta\'’ MMMM yyyy HH:mm:ss',
  'EEEE, d \'ta\'’ MMMM yyyy',
  'EEEE, d \'ta\'’ MMMM y',
  'dd MMM yyyy HH:mm:ss',
  'd \'ta\'’ MMMM yyyy',
  'dd/MM/yyyy HH:mm:ss',
  'd \'ta\'’ MMMM y',
  'MMMM \'ta\'’ yyyy',
  'HH:mm:ss zzzz',
  'dd MMM yyyy',
  'HH:mm:ss z',
  'dd/MM/yyyy',
  'HH:mm:ss',
  'dd MMM y',
  'MMMM dd',
  'dd/MM/y',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];