formats["nb-no"] = [
  'dd. MMMM yyyy \'kl \'HH.mm',
  'd. MMMM yyyy \'kl \'HH.mm',
  'dd.MM.yyyy \'kl \'HH.mm',
  'dd. MMMM yyyy HH.mm.ss',
  'dd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH.mm.ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy H:mm:ss',
  'dd.MM.yy \'kl \'HH.mm',
  'd. MMMM yyyy H:mm:ss',
  'd.M.yy \'kl \'HH.mm',
  'dd. MMMM yyyy HH.mm',
  'dd. MMMM yyyy HH:mm',
  'dd.MM.yyyy HH.mm.ss',
  'dd.MM.yyyy HH:mm:ss',
  'd. MMMM yyyy HH.mm',
  'd. MMMM yyyy HH:mm',
  'dd. MMMM yyyy H:mm',
  'dd.MM.yyyy H:mm:ss',
  'd. MMMM yyyy H:mm',
  'dd.MM.yy HH.mm.ss',
  'dd.MM.yy HH:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH.mm',
  'dd.MM.yyyy HH:mm',
  'd.M.yy HH.mm.ss',
  'd.M.yy HH:mm:ss',
  'dd.MM.yyyy H:mm',
  'EEEE d. MMMM y',
  'd.M.yy H:mm:ss',
  'dd.MM.yy HH.mm',
  'dd.MM.yy HH:mm',
  'HH.mm.ss zzzz',
  'dd. MMMM yyyy',
  'dd.MM.yy H:mm',
  '\'kl \'HH.mm',
  'd. MMMM yyyy',
  'd.M.yy HH.mm',
  'd.M.yy HH:mm',
  'd.M.yy H:mm',
  'HH.mm.ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'd. MMMM y',
  'HH.mm.ss',
  'HH:mm:ss',
  'd. MMM y',
  'dd.MM.yy',
  'H:mm:ss',
  'd. MMMM',
  'dd.MM.y',
  'd.M.yy',
  'HH.mm',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd \'kl \'HH.mm',
  'yyyy-MM-dd HH.mm.ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH.mm',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];