formats["ne-np"] = [
  'EEEE, MMMM dd, yyyy hh:mm:ss a',
  'EEEE, dd MMMM, yyyy hh:mm:ss a',
  'EEEE, MMMM dd, yyyy h:mm:ss a',
  'EEEE, dd MMMM, yyyy h:mm:ss a',
  'EEEE, MMMM dd, yyyy HH:mm:ss',
  'EEEE, dd MMMM, yyyy HH:mm:ss',
  'EEEE, MMMM dd, yyyy H:mm:ss',
  'EEEE, dd MMMM, yyyy H:mm:ss',
  'MMMM dd, yyyy hh:mm:ss a',
  'dd MMMM, yyyy hh:mm:ss a',
  'MMMM dd, yyyy h:mm:ss a',
  'dd MMMM, yyyy h:mm:ss a',
  'MMMM dd, yyyy HH:mm:ss',
  'dd MMMM, yyyy HH:mm:ss',
  'MM/dd/yyyy hh:mm:ss a',
  'MMMM dd, yyyy H:mm:ss',
  'dd MMMM, yyyy H:mm:ss',
  'MM/dd/yyyy h:mm:ss a',
  'dd-MMM-yy hh:mm:ss a',
  'EEEE, MMMM dd, yyyy',
  'EEEE, dd MMMM, yyyy',
  'M/d/yyyy hh:mm:ss a',
  'MM/dd/yy hh:mm:ss a',
  'MM/dd/yyyy HH:mm:ss',
  'dd-MMM-yy h:mm:ss a',
  'M/d/yyyy h:mm:ss a',
  'MM/dd/yy h:mm:ss a',
  'MM/dd/yyyy H:mm:ss',
  'dd-MMM-yy HH:mm:ss',
  'M/d/yy hh:mm:ss a',
  'M/d/yyyy HH:mm:ss',
  'MM/dd/yy HH:mm:ss',
  'dd-MMM-yy H:mm:ss',
  'M/d/yy h:mm:ss a',
  'M/d/yyyy H:mm:ss',
  'MM/dd/yy H:mm:ss',
  'M/d/yy HH:mm:ss',
  'M/d/yy H:mm:ss',
  'HH:mm:ss zzzz',
  'MMMM dd, yyyy',
  'dd MMMM, yyyy',
  'HH:mm:ss z',
  'MM/dd/yyyy',
  'hh:mm:ss a',
  'MMMM,yyyy',
  'dd-MMM-yy',
  'h:mm:ss a',
  'HH:mm:ss',
  'M/d/yyyy',
  'MM/dd/yy',
  'H:mm:ss',
  'MMMM dd',
  'M/d/yy',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yy/MM/dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yy/MM/dd h:mm:ss a',
  'yyyy-MM-dd H:mm:ss',
  'yy/MM/dd HH:mm:ss',
  'yy/MM/dd H:mm:ss',
  'y MMMM d, EEEE',
  'yyyy-MM-dd',
  'y MMMM d',
  'yy/MM/dd',
  'y MMM d',
  'y-MM-dd'
];