formats["nl-be"] = [
  'EEEE d MMMM yyyy H.mm\' u.\'',
  'EEEE d MMMM yyyy HH:mm:ss',
  'EEEE d MMMM yyyy H:mm:ss',
  'd MMMM yyyy H.mm\' u.\'',
  'EEEE d MMMM yyyy HH:mm',
  'EEEE d MMMM yyyy H:mm',
  'd/MM/yyyy H.mm\' u.\'',
  'dd MMM yy H.mm\' u.\'',
  'dd-MMM-yy H.mm\' u.\'',
  'd MMMM yyyy HH:mm:ss',
  'dd-MM-yy H.mm\' u.\'',
  'dd.MM.yy H.mm\' u.\'',
  'd MMMM yyyy H:mm:ss',
  'd/MM/yy H.mm\' u.\'',
  'd/MM/yyyy HH:mm:ss',
  'dd MMM yy HH:mm:ss',
  'dd-MMM-yy HH:mm:ss',
  'd MMMM yyyy HH:mm',
  'd/MM/yyyy H:mm:ss',
  'dd MMM yy H:mm:ss',
  'dd-MM-yy HH:mm:ss',
  'dd-MMM-yy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'EEEE d MMMM yyyy',
  'd MMMM yyyy H:mm',
  'd/MM/yy HH:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'd/MM/yy H:mm:ss',
  'd/MM/yyyy HH:mm',
  'dd MMM yy HH:mm',
  'dd-MMM-yy HH:mm',
  'd/MM/yyyy H:mm',
  'dd MMM yy H:mm',
  'dd-MM-yy HH:mm',
  'dd-MMM-yy H:mm',
  'dd.MM.yy HH:mm',
  'EEEE d MMMM y',
  'HH:mm:ss zzzz',
  'd/MM/yy HH:mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H:mm',
  'd/MM/yy H:mm',
  'H.mm\' u.\'',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'MMMM yyyy',
  'd/MM/yyyy',
  'dd MMM yy',
  'dd-MMM-yy',
  'HH:mm:ss',
  'd MMMM y',
  'dd-MM-yy',
  'dd.MM.yy',
  'H:mm:ss',
  'd MMM y',
  'd/MM/yy',
  'dd MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd H.mm\' u.\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];