formats["nl-nl"] = [
  'EEEE d MMMM yyyy HH.mm.ss\' uur\'',
  'EEEE d MMMM yyyy HH:mm:ss\' uur\'',
  'EEEE d MMMM yyyy HH.mm\' uur\'',
  'EEEE d MMMM yyyy HH:mm\' uur\'',
  'd MMMM yyyy HH.mm.ss\' uur\'',
  'd MMMM yyyy HH:mm:ss\' uur\'',
  'EEEE d MMMM yyyy HH:mm:ss',
  'd MMM yy HH.mm.ss\' uur\'',
  'd MMM yy HH:mm:ss\' uur\'',
  'd MMMM yyyy HH.mm\' uur\'',
  'd MMMM yyyy HH:mm\' uur\'',
  'd-M-yyyy HH.mm.ss\' uur\'',
  'd-M-yyyy HH:mm:ss\' uur\'',
  'd-MMM-yy HH.mm.ss\' uur\'',
  'd-MMM-yy HH:mm:ss\' uur\'',
  'dd-MM-yy HH.mm.ss\' uur\'',
  'dd-MM-yy HH:mm:ss\' uur\'',
  'dd.MM.yy HH.mm.ss\' uur\'',
  'dd.MM.yy HH:mm:ss\' uur\'',
  'dd/MM/yy HH.mm.ss\' uur\'',
  'dd/MM/yy HH:mm:ss\' uur\'',
  'EEEE d MMMM yyyy H:mm:ss',
  'd-M-yy HH.mm.ss\' uur\'',
  'd-M-yy HH:mm:ss\' uur\'',
  'EEEE d MMMM yyyy HH:mm',
  'd MMM yy HH.mm\' uur\'',
  'd MMM yy HH:mm\' uur\'',
  'd-M-yyyy HH.mm\' uur\'',
  'd-M-yyyy HH:mm\' uur\'',
  'd-MMM-yy HH.mm\' uur\'',
  'd-MMM-yy HH:mm\' uur\'',
  'dd-MM-yy HH.mm\' uur\'',
  'dd-MM-yy HH:mm\' uur\'',
  'dd.MM.yy HH.mm\' uur\'',
  'dd.MM.yy HH:mm\' uur\'',
  'dd/MM/yy HH.mm\' uur\'',
  'dd/MM/yy HH:mm\' uur\'',
  'EEEE d MMMM yyyy H.mm',
  'EEEE d MMMM yyyy H:mm',
  'd MMMM yyyy HH:mm:ss',
  'd-M-yy HH.mm\' uur\'',
  'd-M-yy HH:mm\' uur\'',
  'd MMMM yyyy H:mm:ss',
  'd MMM yy HH:mm:ss',
  'd MMMM yyyy HH:mm',
  'd-M-yyyy HH:mm:ss',
  'd-MMM-yy HH:mm:ss',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'EEEE d MMMM yyyy',
  'HH.mm.ss\' uur\'',
  'HH:mm:ss\' uur\'',
  'd MMM yy H:mm:ss',
  'd MMMM yyyy H.mm',
  'd MMMM yyyy H:mm',
  'd-M-yyyy H:mm:ss',
  'd-MMM-yy H:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd.MM.yy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'd-M-yy HH:mm:ss',
  'd MMM yy HH:mm',
  'd-M-yy H:mm:ss',
  'd-M-yyyy HH:mm',
  'd-MMM-yy HH:mm',
  'dd-MM-yy HH:mm',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'EEEE d MMMM y',
  'HH.mm\' uur\'',
  'HH:mm:ss zzzz',
  'HH:mm\' uur\'',
  'd MMM yy H.mm',
  'd MMM yy H:mm',
  'd-M-yyyy H.mm',
  'd-M-yyyy H:mm',
  'd-MMM-yy H.mm',
  'd-MMM-yy H:mm',
  'dd-MM-yy H.mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H.mm',
  'dd.MM.yy H:mm',
  'dd/MM/yy H.mm',
  'dd/MM/yy H:mm',
  'd-M-yy HH:mm',
  'd MMMM yyyy',
  'd-M-yy H.mm',
  'd-M-yy H:mm',
  'HH:mm:ss z',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMM yy',
  'd MMMM y',
  'd-M-yyyy',
  'd-MMM-yy',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'dd MMMM',
  'd-M-yy',
  'HH:mm',
  'H.mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH.mm.ss\' uur\'',
  'yyyy-MM-dd HH:mm:ss\' uur\'',
  'yyyy-MM-dd HH.mm\' uur\'',
  'yyyy-MM-dd HH:mm\' uur\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H.mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];