formats["pl-pl"] = [
  'dd MMMM yyyy HH:mm:ss',
  'd MMMM yyyy HH:mm:ss',
  'dd MMMM yyyy H:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'dd MMMM yyyy HH:mm',
  'd MMMM yyyy HH:mm',
  'dd MMMM yyyy H:mm',
  'd MMMM yyyy H:mm',
  'EEEE, d MMMM y',
  'HH:mm:ss zzzz',
  'dd MMMM yyyy',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'H:mm:ss',
  'dd.MM.y',
  'd MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy-MM-dd HH:mm:ss',
  'yy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yy-MM-dd HH:mm',
  'yy-MM-dd H:mm',
  'yyyy-MM-dd',
  'yy-MM-dd'
];