formats["pt-br"] = [
  'EEEE, d\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'EEEE, d\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, d\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE, d\' de \'MMMM\' de \'yyyy H:mm',
  'd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, d\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy HH:mm',
  'd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE, d \'de\' MMMM \'de\' y',
  'd\' de \'MMMM\' de \'yyyy',
  'd \'de\' MMMM \'de\' y',
  'd \'de\' MMM \'de\' y',
  'dd-MM-yyyy HH:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'dd/MM/yyyy HH:mm:ss',
  'dd-MM-yyyy H:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'dd/MM/yyyy H:mm:ss',
  'd-M-yyyy HH:mm:ss',
  'd.M.yyyy HH:mm:ss',
  'd/M/yyyy HH:mm:ss',
  'dd-MM-yy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MMMM\' de \'yyyy',
  'd-M-yyyy H:mm:ss',
  'd.M.yyyy H:mm:ss',
  'd/M/yyyy H:mm:ss',
  'dd-MM-yy H:mm:ss',
  'dd-MM-yyyy HH:mm',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yyyy HH:mm',
  'd-M-yy HH:mm:ss',
  'd.M.yy HH:mm:ss',
  'd/M/yy HH:mm:ss',
  'dd-MM-yyyy H:mm',
  'dd.MM.yyyy H:mm',
  'dd/MM/yyyy H:mm',
  'd-M-yy H:mm:ss',
  'd-M-yyyy HH:mm',
  'd.M.yy H:mm:ss',
  'd.M.yyyy HH:mm',
  'd/M/yy H:mm:ss',
  'd/M/yyyy HH:mm',
  'dd-MM-yy HH:mm',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'dd\' de \'MMMM',
  'HH:mm:ss zzzz',
  'd-M-yyyy H:mm',
  'd.M.yyyy H:mm',
  'd/M/yyyy H:mm',
  'dd-MM-yy H:mm',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'd-M-yy HH:mm',
  'd.M.yy HH:mm',
  'd/M/yy HH:mm',
  'd-M-yy H:mm',
  'd.M.yy H:mm',
  'd/M/yy H:mm',
  'HH:mm:ss z',
  'dd-MM-yyyy',
  'dd.MM.yyyy',
  'dd/MM/yyyy',
  'HH:mm:ss',
  'd-M-yyyy',
  'd.M.yyyy',
  'd/M/yyyy',
  'dd-MM-yy',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'd-M-yy',
  'd.M.yy',
  'd/M/yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy.MM.dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy.MM.dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy.MM.dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy.MM.dd H:mm',
  'yyyy-MM-dd',
  'yyyy.MM.dd'
];