formats["pt-pt"] = [
  'EEEE, d\' de \'MMMM\' de \'yyyy HH\'H\'mm\'m\'',
  'EEEE, d\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd\' de \'MMMM\' de \'yyyy HH\'H\'mm\'m\'',
  'EEEE, d\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, d\' de \'MMMM\' de \'yyyy HH:mm',
  'EEEE, d\' de \'MMMM\' de \'yyyy H:mm',
  'd\' de \'MMMM\' de \'yyyy HH:mm:ss',
  'd\' de \'MMMM\' de \'yyyy H:mm:ss',
  'EEEE, d\' de \'MMMM\' de \'yyyy',
  'd\' de \'MMMM\' de \'yyyy HH:mm',
  'd\' de \'MMMM\' de \'yyyy H:mm',
  'EEEE, d \'de\' MMMM \'de\' y',
  'd\' de \'MMMM\' de \'yyyy',
  'dd-MM-yyyy HH\'H\'mm\'m\'',
  'd.MMM.yy HH\'H\'mm\'m\'',
  'd/MMM/yy HH\'H\'mm\'m\'',
  'dd/MM/yy HH\'H\'mm\'m\'',
  'd \'de\' MMMM \'de\' y',
  'd.M.yy HH\'H\'mm\'m\'',
  'dd-MM-yyyy HH:mm:ss',
  'dd-MM-yyyy H:mm:ss',
  'd.MMM.yy HH:mm:ss',
  'd/MMM/yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MMMM\' de \'yyyy',
  'd.MMM.yy H:mm:ss',
  'd/MMM/yy H:mm:ss',
  'dd-MM-yyyy HH:mm',
  'dd/MM/yy H:mm:ss',
  'd.M.yy HH:mm:ss',
  'dd-MM-yyyy H:mm',
  'HH\'H\'mm\'m\'',
  'd.M.yy H:mm:ss',
  'd.MMM.yy HH:mm',
  'd/MMM/yy HH:mm',
  'dd/MM/yy HH:mm',
  'HH:mm:ss zzzz',
  'd.MMM.yy H:mm',
  'd/MMM/yy H:mm',
  'dd/MM/yy H:mm',
  'd.M.yy HH:mm',
  'd.M.yy H:mm',
  'HH:mm:ss z',
  'dd-MM-yyyy',
  'HH:mm:ss',
  'd.MMM.yy',
  'd/MMM/yy',
  'dd/MM/yy',
  'H:mm:ss',
  'dd/MM/y',
  'd.M.yy',
  'HH:mm',
  'H:mm',
  'd/M',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH\'H\'mm\'m\'',
  'yy.MM.dd HH\'H\'mm\'m\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy.MM.dd HH:mm:ss',
  'yy.MM.dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yy.MM.dd HH:mm',
  'yy.MM.dd H:mm',
  'yyyy-MM-dd',
  'yy.MM.dd'
];