formats["ro-ro"] = [
  'd MMMM yyyy HH:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'd MMMM yyyy HH:mm',
  'd.M.yyyy HH:mm:ss',
  'd MMMM yyyy H:mm',
  'd.M.yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd.MM.yyyy H:mm',
  'EEEE, d MMMM y',
  'd.M.yyyy HH:mm',
  'HH:mm:ss zzzz',
  'd.M.yyyy H:mm',
  'd MMMM yyyy',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'd.M.yyyy',
  'H:mm:ss',
  'd MMM y',
  'dd.MM.y',
  'd MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];