formats["ru-md"] = [
  'EEEE, d MMMM yyyy \'г\'. H:mm:ss',
  'd MMMM yyyy \'г\'. H:mm:ss',
  'd MMM yyyy \'г\'. H:mm:ss',
  'EEEE, d MMMM yyyy \'г\'.',
  'EEEE, d MMMM y \'г\'.',
  'd MMMM yyyy \'г\'.',
  'dd.MM.yyyy H:mm:ss',
  'd MMM yyyy \'г\'.',
  'd MMMM y \'г\'.',
  'd MMM y \'г\'.',
  'H:mm:ss zzzz',
  'dd.MM.yyyy',
  'H:mm:ss z',
  'MMMM yyyy',
  'dd.MM.yy',
  'H:mm:ss',
  'MMMM dd',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];