formats["ru-ru"] = [
  'dd MMMM yyyy \'г.\' HH:mm:ss',
  'd MMMM yyyy \'г.\' HH:mm:ss',
  'dd MMMM yyyy \'г.\' H:mm:ss',
  'd MMMM yyyy \'г.\' H:mm:ss',
  'dd MMMM yyyy \'г.\' HH:mm',
  'd MMMM yyyy \'г.\' HH:mm',
  'dd MMMM yyyy \'г.\' H:mm',
  'd MMMM yyyy \'г.\' H:mm',
  'EEEE, d MMMM y \'г\'.',
  'dd MMMM yyyy \'г.\'',
  'dd.MM.yyyy HH:mm:ss',
  'd MMMM yyyy \'г.\'',
  'dd.MM.yyyy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'MMMM yyyy \'г.\'',
  'd MMMM y \'г\'.',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd/MM/yy H:mm:ss',
  'd MMM y \'г\'.',
  'd.M.yy HH:mm:ss',
  'dd.MM.yyyy H:mm',
  'd.M.yy H:mm:ss',
  'dd.MM.yy HH:mm',
  'dd/MM/yy HH:mm',
  'dd.MM.yy H:mm',
  'dd/MM/yy H:mm',
  'H:mm:ss zzzz',
  'd.M.yy HH:mm',
  'd.M.yy H:mm',
  'dd.MM.yyyy',
  'H:mm:ss z',
  'MMMM yyyy',
  'HH:mm:ss',
  'dd.MM.yy',
  'dd/MM/yy',
  'H:mm:ss',
  'MMMM dd',
  'd.M.yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];