formats["sah-ru"] = [
  'EEEE, MMMM d \'күнэ\' yyyy \'с.\' HH:mm:ss',
  'EEEE, yyyy \'с.\' MMMM d \'күнэ\' HH:mm:ss',
  'EEEE, MMMM d \'күнэ\' yyyy \'с.\' H:mm:ss',
  'EEEE, yyyy \'с.\' MMMM d \'күнэ\' H:mm:ss',
  'EEEE, MMMM d \'күнэ\' yyyy \'с.\'',
  'EEEE, yyyy \'с.\' MMMM d \'күнэ\'',
  'dd yyyy MM d HH:mm:ss',
  'dd yyyy MM d H:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'd.M.yyyy HH:mm:ss',
  'd.M.yyyy H:mm:ss',
  'HH:mm:ss zzzz',
  'dd yyyy MM d',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'HH:mm:ss',
  'd.M.yyyy',
  'H:mm:ss',
  'MMMM dd',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'y \'сыл\' MMMM d \'күнэ\', EEEE',
  'yyyy \'с.\' MMMM d \'күнэ\' HH:mm:ss',
  'yyyy \'с.\' MMMM d \'күнэ\' H:mm:ss',
  'yyyy \'с.\' MMMM d \'күнэ\'',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy MM d HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy MM d H:mm:ss',
  'yyyy \'с.\' MMMM',
  'yyyy-MM-dd',
  'y, MMMM d',
  'yyyy MM d',
  'y, MMM d',
  'yy/M/d'
];