formats["se-fi"] = [
  'EEEE\', \'MMMM d\'. b. \'yyyy HH:mm:ss',
  'EEEE\', \'MMMM d\'. b. \'yyyy H:mm:ss',
  'EEEE\', \'MMMM d\'. b. \'yyyy',
  'MMMM d\'. b. \'yyyy HH:mm:ss',
  'MMMM d\'. b. \'yyyy H:mm:ss',
  'MMMM d\'. b. \'yyyy',
  'dd.MM.yyyy HH:mm:ss',
  'dd.MM.yyyy H:mm:ss',
  'd.M.yyyy HH:mm:ss',
  'd.M.yyyy H:mm:ss',
  'd.M.yy HH:mm:ss',
  'd.M.yy H:mm:ss',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd.M.yyyy',
  'H:mm:ss',
  'MMMM dd',
  'd.M.yy',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'y MMMM d, EEEE',
  'yyyy-MM-dd',
  'y MMMM d',
  'y MMM d',
  'y-MM-dd'
];