formats["se-se"] = [
  'EEEE, MMMM d\'. b. \'yyyy HH:mm:ss',
  'EEEE, MMMM d\'. b. \'yyyy H:mm:ss',
  'MMMM d\'. b. \'yyyy HH:mm:ss',
  'MMMM d\'. b. \'yyyy H:mm:ss',
  'EEEE, MMMM d\'. b. \'yyyy',
  'MMMM d\'. b. \'yyyy',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'MMMM yyyy',
  'HH:mm:ss',
  'H:mm:ss',
  'MMMM dd',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy-MM-dd HH:mm:ss',
  'yy-MM-dd H:mm:ss',
  'y MMMM d, EEEE',
  'yyyy-MM-dd',
  'y MMMM d',
  'yy-MM-dd',
  'y MMM d',
  'y-MM-dd'
];