formats["si-lk"] = [
  'a h.mm.ss zzzz',
  'a h.mm.ss z',
  'a h.mm.ss',
  'HH:mm:ss',
  'MMMM dd',
  'a h.mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy MMMM d, EEEE a h.mm.ss',
  'yyyy MMMM d, EEEE HH:mm:ss',
  'yyyy MMMM d a h.mm.ss',
  'yyyy MMM d a h.mm.ss',
  'yyyy MMMM d HH:mm:ss',
  'yyyy-MM-dd a h.mm.ss',
  'yyyy MMM d HH:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy MMMM d, EEEE',
  'y MMMM d, EEEE',
  'yyyy MMMM d',
  'yyyy MMM d',
  'yyyy-MM-dd',
  'yyyy MMMM',
  'y MMMM d',
  'y MMM d',
  'y-MM-dd'
];