formats["sk-sk"] = [
  'dd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy H.mm.ss',
  'dd. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy H.mm.ss',
  'd. MMMM yyyy H:mm:ss',
  'd. M. yyyy HH:mm:ss',
  'dd. MMMM yyyy HH:mm',
  'dd.MM.yyyy HH:mm:ss',
  'd. M. yyyy H.mm.ss',
  'd. M. yyyy H:mm:ss',
  'd. MMMM yyyy HH:mm',
  'dd. MMMM yyyy H.mm',
  'dd. MMMM yyyy H:mm',
  'dd.MM.yyyy H.mm.ss',
  'dd.MM.yyyy H:mm:ss',
  'd. M. yy HH:mm:ss',
  'd. MMMM yyyy H.mm',
  'd. MMMM yyyy H:mm',
  'd.M.yyyy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'd. M. yy H.mm.ss',
  'd. M. yy H:mm:ss',
  'd. M. yyyy HH:mm',
  'd.M.yyyy H.mm.ss',
  'd.M.yyyy H:mm:ss',
  'dd.MM.yy H.mm.ss',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'EEEE, d. MMMM y',
  'd. M. yyyy H.mm',
  'd. M. yyyy H:mm',
  'd.M.yy HH:mm:ss',
  'dd.MM.yyyy H.mm',
  'dd.MM.yyyy H:mm',
  'd. M. yy HH:mm',
  'd.M.yy H.mm.ss',
  'd.M.yy H:mm:ss',
  'd.M.yyyy HH:mm',
  'dd.MM.yy HH:mm',
  'd. M. yy H.mm',
  'd. M. yy H:mm',
  'd.M.yyyy H.mm',
  'd.M.yyyy H:mm',
  'dd. MMMM yyyy',
  'dd.MM.yy H.mm',
  'dd.MM.yy H:mm',
  'H:mm:ss zzzz',
  'd. MMMM yyyy',
  'd.M.yy HH:mm',
  'd.M.yy H.mm',
  'd.M.yy H:mm',
  'd. M. yyyy',
  'dd.MM.yyyy',
  'H:mm:ss z',
  'MMMM yyyy',
  'd. MMMM y',
  'HH:mm:ss',
  'd. M. yy',
  'd.M.yyyy',
  'dd.MM.yy',
  'H.mm.ss',
  'H:mm:ss',
  'd. M. y',
  'dd MMMM',
  'd.M.yy',
  'HH:mm',
  'H.mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H.mm.ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H.mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];