formats["sl-si"] = [
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss',
  'EEEE, d. MMMM yyyy HH:mm',
  'EEEE, d. MMMM yyyy H:mm',
  'dd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy H:mm:ss',
  'd. M. yyyy HH:mm:ss',
  'dd. MM. yy HH:mm:ss',
  'dd. MMMM yyyy HH:mm',
  'dd.MM.yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy',
  'd. M. yyyy H:mm:ss',
  'd. MMMM yyyy HH:mm',
  'dd. MM. yy H:mm:ss',
  'dd. MMMM yyyy H:mm',
  'dd.MM.yyyy H:mm:ss',
  'd. M. yy HH:mm:ss',
  'd. MMMM yyyy H:mm',
  'd.M.yyyy HH:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'EEEE, dd. MMMM y',
  'd. M. yy H:mm:ss',
  'd. M. yyyy HH:mm',
  'd.M.yyyy H:mm:ss',
  'dd. MM. yy HH:mm',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'd. M. yyyy H:mm',
  'd.M.yy HH:mm:ss',
  'dd. MM. yy H:mm',
  'dd.MM.yyyy H:mm',
  'd. M. yy HH:mm',
  'd.M.yy H:mm:ss',
  'd.M.yyyy HH:mm',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'd. M. yy H:mm',
  'd.M.yyyy H:mm',
  'dd. MMMM yyyy',
  'dd.MM.yy H:mm',
  'd. MMMM yyyy',
  'd.M.yy HH:mm',
  'd.M.yy H:mm',
  'HH:mm:ss z',
  'd. M. yyyy',
  'dd. MM. yy',
  'dd. MMMM y',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'd. MM. yy',
  'HH:mm:ss',
  'd. M. yy',
  'd. MMM y',
  'd.M.yyyy',
  'dd.MM.yy',
  'H:mm:ss',
  'd. MMMM',
  'd.M.yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];