formats["so-so"] = [
  'EEEE, MMMM dd, yyyy h:mm:ss a',
  'EEEE, MMMM dd, yyyy HH:mm:ss',
  'dd MMMM yyyy h:mm:ss a',
  'dd MMMM yyyy HH:mm:ss',
  'dd-MMM-yyyy h:mm:ss a',
  'dd-MMM-yyyy HH:mm:ss',
  'dd/MM/yyyy h:mm:ss a',
  'EEEE, MMMM dd, yyyy',
  'dd/MM/yyyy HH:mm:ss',
  'EEEE, MMMM dd, y',
  'h:mm:ss a zzzz',
  'dd MMMM yyyy',
  'dd-MMM-yyyy',
  'h:mm:ss a z',
  'dd/MM/yyyy',
  'MMMM yyyy',
  'dd MMMM y',
  'h:mm:ss a',
  'HH:mm:ss',
  'dd-MMM-y',
  'dd/MM/yy',
  'MMMM dd',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];