formats["sq-al"] = [
  'EEEE, d MMMM y',
  'HH:mm:ss zzzz',
  'HH:mm:ss z',
  'h:mm:ss.a',
  'HH:mm:ss',
  'd MMMM y',
  'MMMM dd',
  'd MMM y',
  'd.M.yy',
  'h:mm.a',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd h:mm:ss.a',
  'yyyy-MM-dd HH:mm:ss',
  'yy-MM-dd h:mm:ss.a',
  'yy-MM-dd HH:mm:ss',
  'yyyy-MM-dd h:mm.a',
  'yyyy-MM-dd HH:mm',
  'yy-MM-dd h:mm.a',
  'yy-MM-dd HH:mm',
  'yyyy-MM-dd',
  'yy-MM-dd',
  'yyyy-MM'
];