formats["sr-cyrl-ba"] = [
  'EEEE, d. MMMM yyyy HH:mm:ss',
  'EEEE, d. MMMM yyyy H:mm:ss',
  'dd. MMMM yyyy HH:mm:ss',
  'd. MMMM yyyy HH:mm:ss',
  'dd. MMMM yyyy H:mm:ss',
  'd. MMMM yyyy H:mm:ss',
  'dd.MM.yyyy. HH:mm:ss',
  'dd.MM.yyyy. H:mm:ss',
  'EEEE, d. MMMM yyyy',
  'd.M.yyyy. HH:mm:ss',
  'EEEE, dd. MMMM y.',
  'd.M.yyyy. H:mm:ss',
  'HH:mm:ss zzzz',
  'dd. MMMM yyyy',
  'd. MMMM yyyy',
  'dd. MMMM y.',
  'dd.MM.yyyy.',
  'HH:mm:ss z',
  'MMMM, yyyy',
  'd.M.yyyy.',
  'HH:mm:ss',
  'dd.MM.y.',
  'H:mm:ss',
  'MMMM dd',
  'd.M.yy.',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];