formats["sr-cyrl-me"] = [
  'EEEE, d. MMMM yyyy. HH:mm:ss',
  'EEEE, d. MMMM yyyy. H:mm:ss',
  'dd. MMMM yyyy. HH:mm:ss',
  'd. MMMM yyyy. HH:mm:ss',
  'dd. MMMM yyyy. H:mm:ss',
  'd. MMMM yyyy. H:mm:ss',
  'd. M. yyyy. HH:mm:ss',
  'dd. MM. yy. HH:mm:ss',
  'dd.MM.yyyy. HH:mm:ss',
  'EEEE, d. MMMM yyyy.',
  'd. M. yyyy. H:mm:ss',
  'dd. MM. yy. H:mm:ss',
  'dd.MM.yyyy. H:mm:ss',
  'd. M. yy. HH:mm:ss',
  'd.M.yyyy. HH:mm:ss',
  'dd.MM.yy. HH:mm:ss',
  'EEEE, dd. MMMM y.',
  'd. M. yy. H:mm:ss',
  'd.M.yyyy. H:mm:ss',
  'dd.MM.yy. H:mm:ss',
  'd.M.yy. HH:mm:ss',
  'd.M.yy. H:mm:ss',
  'dd. MMMM yyyy.',
  'HH.mm.ss zzzz',
  'd. MMMM yyyy.',
  'd. M. yyyy.',
  'dd. MM. yy.',
  'dd. MMMM y.',
  'dd.MM.yyyy.',
  'HH.mm.ss z',
  'MMMM yyyy.',
  'd. M. yy.',
  'd.M.yyyy.',
  'dd.MM.yy.',
  'HH.mm.ss',
  'HH:mm:ss',
  'dd.MM.y.',
  'H:mm:ss',
  'MMMM dd',
  'd.M.yy.',
  'HH.mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd. HH:mm:ss',
  'yyyy-MM-dd. H:mm:ss',
  'yyyy-MM-dd.'
];