formats["sv-fi"] = [
  '\'den \'d MMMM yyyy \'kl \'H:mm',
  '\'den \'d MMMM yyyy HH:mm:ss',
  '\'den \'d MMMM yyyy H:mm:ss',
  '\'den \'d MMMM yyyy HH:mm',
  '\'den \'d MMMM yyyy H:mm',
  'dd.MM.yyyy \'kl \'H:mm',
  '\'kl\'. HH:mm:ss zzzz',
  'd.M.yyyy \'kl \'H:mm',
  '\'den \'d MMMM yyyy',
  'dd.MM.yyyy HH:mm:ss',
  'd.M.yy \'kl \'H:mm',
  'dd.MM.yyyy H:mm:ss',
  'd.M.yyyy HH:mm:ss',
  'd.M.yyyy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'd.M.yy HH:mm:ss',
  'dd.MM.yyyy H:mm',
  '\'den \'d MMMM',
  'd.M.yy H:mm:ss',
  'd.M.yyyy HH:mm',
  'EEEE d MMMM y',
  'd.M.yyyy H:mm',
  'd.M.yy HH:mm',
  '\'kl \'H:mm',
  'd.M.yy H:mm',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'd.M.yyyy',
  'H:mm:ss',
  'd MMM y',
  'dd-MM-y',
  'd.M.yy',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd \'kl \'H:mm',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];