formats["sv-se"] = [
  '\'den \'d MMMM yyyy \'kl \'H:mm',
  '\'den \'d MMMM yyyy HH:mm:ss',
  '\'den \'d MMMM yyyy H:mm:ss',
  '\'den \'d MMMM yyyy HH:mm',
  '\'den \'d MMMM yyyy H:mm',
  '\'kl\'. HH:mm:ss zzzz',
  '\'den \'d MMMM yyyy',
  '\'den \'d MMMM',
  'EEEE d MMMM y',
  '\'kl \'H:mm',
  'HH:mm:ss z',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'H:mm:ss',
  'd MMM y',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd \'kl \'H:mm',
  'yy-MM-dd \'kl \'H:mm',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yy-MM-dd HH:mm:ss',
  'yy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yy-MM-dd HH:mm',
  'yy-MM-dd H:mm',
  'yyyy-MM-dd',
  'yy-MM-dd',
  'y-MM-dd'
];