formats["sw-ke"] = [
  'EEEE, MMMM dd, yyyy hh:mm:ss a',
  'EEEE, dd MMMM, yyyy hh:mm:ss a',
  'EEEE, MMMM dd, yyyy h:mm:ss a',
  'EEEE, dd MMMM, yyyy h:mm:ss a',
  'EEEE, MMMM dd, yyyy HH:mm:ss',
  'EEEE, dd MMMM, yyyy HH:mm:ss',
  'EEEE, MMMM dd, yyyy H:mm:ss',
  'EEEE, MMMM dd, yyyy hh:mm a',
  'EEEE, dd MMMM, yyyy H:mm:ss',
  'EEEE, dd MMMM, yyyy hh:mm a',
  'EEEE, MMMM dd, yyyy h:mm a',
  'EEEE, dd MMMM, yyyy h:mm a',
  'EEEE, MMMM dd, yyyy HH:mm',
  'EEEE, dd MMMM, yyyy HH:mm',
  'EEEE, MMMM dd, yyyy H:mm',
  'EEEE, dd MMMM, yyyy H:mm',
  'MMMM dd, yyyy hh:mm:ss a',
  'dd MMMM, yyyy hh:mm:ss a',
  'MMMM dd, yyyy h:mm:ss a',
  'dd MMMM, yyyy h:mm:ss a',
  'MMMM dd, yyyy HH:mm:ss',
  'dd MMMM, yyyy HH:mm:ss',
  'MM/dd/yyyy hh:mm:ss a',
  'MMMM dd, yyyy H:mm:ss',
  'MMMM dd, yyyy hh:mm a',
  'dd MMMM, yyyy H:mm:ss',
  'dd MMMM, yyyy hh:mm a',
  'MM/dd/yyyy h:mm:ss a',
  'MMMM dd, yyyy h:mm a',
  'dd MMMM, yyyy h:mm a',
  'dd-MMM-yy hh:mm:ss a',
  'EEEE, MMMM dd, yyyy',
  'EEEE, dd MMMM, yyyy',
  'M/d/yyyy hh:mm:ss a',
  'MM/dd/yy hh:mm:ss a',
  'MM/dd/yyyy HH:mm:ss',
  'MMMM dd, yyyy HH:mm',
  'dd MMMM, yyyy HH:mm',
  'dd-MMM-yy h:mm:ss a',
  'M/d/yyyy h:mm:ss a',
  'MM/dd/yy h:mm:ss a',
  'MM/dd/yyyy H:mm:ss',
  'MM/dd/yyyy hh:mm a',
  'MMMM dd, yyyy H:mm',
  'dd MMMM, yyyy H:mm',
  'dd-MMM-yy HH:mm:ss',
  'M/d/yy hh:mm:ss a',
  'M/d/yyyy HH:mm:ss',
  'MM/dd/yy HH:mm:ss',
  'MM/dd/yyyy h:mm a',
  'dd-MMM-yy H:mm:ss',
  'dd-MMM-yy hh:mm a',
  'M/d/yy h:mm:ss a',
  'M/d/yyyy H:mm:ss',
  'M/d/yyyy hh:mm a',
  'MM/dd/yy H:mm:ss',
  'MM/dd/yy hh:mm a',
  'MM/dd/yyyy HH:mm',
  'dd-MMM-yy h:mm a',
  'M/d/yy HH:mm:ss',
  'M/d/yyyy h:mm a',
  'MM/dd/yy h:mm a',
  'MM/dd/yyyy H:mm',
  'dd-MMM-yy HH:mm',
  'EEEE, d MMMM y',
  'M/d/yy H:mm:ss',
  'M/d/yy hh:mm a',
  'M/d/yyyy HH:mm',
  'MM/dd/yy HH:mm',
  'dd-MMM-yy H:mm',
  'h:mm:ss a zzzz',
  'M/d/yy h:mm a',
  'M/d/yyyy H:mm',
  'MM/dd/yy H:mm',
  'MMMM dd, yyyy',
  'dd MMMM, yyyy',
  'M/d/yy HH:mm',
  'M/d/yy H:mm',
  'h:mm:ss a z',
  'MM/dd/yyyy',
  'MMMM, yyyy',
  'hh:mm:ss a',
  'dd-MMM-yy',
  'h:mm:ss a',
  'HH:mm:ss',
  'M/d/yyyy',
  'MM/dd/yy',
  'd MMMM y',
  'H:mm:ss',
  'MMMM dd',
  'd MMM y',
  'dd/MM/y',
  'hh:mm a',
  'M/d/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yy/MM/dd hh:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yy/MM/dd h:mm:ss a',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yy/MM/dd HH:mm:ss',
  'yyyy-MM-dd h:mm a',
  'yy/MM/dd H:mm:ss',
  'yy/MM/dd hh:mm a',
  'yyyy-MM-dd HH:mm',
  'yy/MM/dd h:mm a',
  'yyyy-MM-dd H:mm',
  'yy/MM/dd HH:mm',
  'yy/MM/dd H:mm',
  'yyyy-MM-dd',
  'yy/MM/dd'
];