formats["th-th"] = [
  'H นาฬิกา mm นาที ss วินาที zzzz',
  'H นาฬิกา mm นาที ss วินาที z',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy hh:mm:ss a',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy h:mm:ss a',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy HH:mm:ss',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy H:mm:ss',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy hh:mm a',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy h:mm a',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy HH:mm',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy H:mm',
  '\'วัน\'EEEE\'ที่\' d MMMM G yyyy',
  'EEE d MMMM yyyy hh:mm:ss a',
  'EEE d MMMM yyyy h:mm:ss a',
  'EEE d MMMM yyyy HH:mm:ss',
  'EEEEที่ d MMMM G y',
  'EEE d MMMM yyyy H:mm:ss',
  'EEE d MMMM yyyy hh:mm a',
  'EEE d MMMM yyyy h:mm a',
  'd MMMM yyyy hh:mm:ss a',
  'dd MMM yyyy hh:mm:ss a',
  'EEE d MMMM yyyy HH:mm',
  'd MMM yyyy hh:mm:ss a',
  'd MMMM yyyy h:mm:ss a',
  'dd MMM yyyy h:mm:ss a',
  'dd/MM/yyyy hh:mm:ss a',
  'EEE d MMMM yyyy H:mm',
  'd MMM yyyy h:mm:ss a',
  'd MMMM yyyy HH:mm:ss',
  'dd MMM yyyy HH:mm:ss',
  'dd/MM/yyyy h:mm:ss a',
  'd MMM yyyy HH:mm:ss',
  'd MMMM yyyy H:mm:ss',
  'd MMMM yyyy hh:mm a',
  'd/M/yyyy hh:mm:ss a',
  'dd MMM yyyy H:mm:ss',
  'dd MMM yyyy hh:mm a',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'd MMM yyyy H:mm:ss',
  'd MMM yyyy hh:mm a',
  'd MMMM yyyy h:mm a',
  'd/M/yyyy h:mm:ss a',
  'dd MMM yyyy h:mm a',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'd MMM yyyy h:mm a',
  'd MMMM yyyy HH:mm',
  'd/M/yy hh:mm:ss a',
  'd/M/yyyy HH:mm:ss',
  'dd MMM yyyy HH:mm',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yyyy h:mm a',
  'd MMM yyyy HH:mm',
  'd MMMM yyyy H:mm',
  'd/M/yy h:mm:ss a',
  'd/M/yyyy H:mm:ss',
  'd/M/yyyy hh:mm a',
  'dd MMM yyyy H:mm',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'EEE d MMMM yyyy',
  'd MMM yyyy H:mm',
  'd/M/yy HH:mm:ss',
  'd/M/yyyy h:mm a',
  'dd/MM/yy h:mm a',
  'dd/MM/yyyy H:mm',
  'd/M/yy H:mm:ss',
  'd/M/yy hh:mm a',
  'd/M/yyyy HH:mm',
  'dd/MM/yy HH:mm',
  'd/M/yy h:mm a',
  'd/M/yyyy H:mm',
  'dd/MM/yy H:mm',
  'd/M/yy HH:mm',
  'd MMMM yyyy',
  'd/M/yy H:mm',
  'dd MMM yyyy',
  'd MMM yyyy',
  'd MMMM G y',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'd/M/yyyy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMM y',
  'dd MMMM',
  'hh:mm a',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];