formats["tr-tr"] = [
  'dd MMMM yyyy dddd HH:mm:ss',
  'dd MMMM yyyy dddd HH:mm',
  'dd MMMM yyyy HH:mm:ss',
  'dd.MM.yyyy HH:mm:ss',
  'dd MMMM yyyy HH:mm',
  'dd MMMM yyyy dddd',
  'dd.MM.yy HH:mm:ss',
  'dd.MM.yyyy HH:mm',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'd MMMM y EEEE',
  'dd MMMM yyyy',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'MMMM yyyy',
  'HH:mm:ss',
  'd MMMM y',
  'dd.MM.yy',
  'd MMM y',
  'dd MMMM',
  'd MM y',
  'HH:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd'
];