formats["uk-ua"] = [
  'd MMMM yyyy\' р.\' HH:mm:ss',
  'd MMMM yyyy\' р.\' H:mm:ss',
  'd MMMM yyyy\' р.\' HH:mm',
  'd MMMM yyyy\' р.\' H:mm',
  'EEEE, d MMMM y \'р\'.',
  'dd.MM.yyyy HH:mm:ss',
  'd MMMM yyyy\' р.\'',
  'dd.MM.yyyy H:mm:ss',
  'dd.MM.yy HH:mm:ss',
  'MMMM yyyy\' р.\'',
  'd MMMM y \'р\'.',
  'dd.MM.yy H:mm:ss',
  'dd.MM.yyyy HH:mm',
  'd MMM y \'р\'.',
  'dd.MM.yyyy H:mm',
  'dd.MM.yy HH:mm',
  'HH:mm:ss zzzz',
  'dd.MM.yy H:mm',
  'HH:mm:ss z',
  'dd.MM.yyyy',
  'HH:mm:ss',
  'dd.MM.yy',
  'H:mm:ss',
  'd MMMM',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];