formats["ur-in"] = [
  'EEEE, d MMMM, yyyy h:mm:ss a',
  'EEEE, d MMMM, yyyy H:mm:ss',
  'd MMMM, yyyy h:mm:ss a',
  'd MMM, yyyy h:mm:ss a',
  'd MMMM, yyyy H:mm:ss',
  'd MMM, yyyy H:mm:ss',
  'EEEE, d MMMM, yyyy',
  'EEEE، d MMMM، y',
  'd/M/yy h:mm:ss a',
  'd/M/yy H:mm:ss',
  'h:mm:ss a zzzz',
  'd MMMM, yyyy',
  'd MMM, yyyy',
  'h:mm:ss a z',
  'd MMMM، y',
  'MMMM yyyy',
  'd MMM، y',
  'h:mm:ss a',
  'H:mm:ss',
  'MMMM dd',
  'd/M/yy',
  'h:mm a',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss'
];