formats["ur-pk"] = [
  'EEEE, dd MMMM, yyyy hh:mm:ss a',
  'EEEE, dd MMMM, yyyy h:mm:ss a',
  'EEEE, dd MMMM, yyyy HH:mm:ss',
  'EEEE, dd MMMM, yyyy H:mm:ss',
  'EEEE, dd MMMM, yyyy hh:mm a',
  'EEEE, dd MMMM, yyyy h:mm a',
  'EEEE, dd MMMM, yyyy HH:mm',
  'EEEE, dd MMMM, yyyy H:mm',
  'dd MMMM, yyyy hh:mm:ss a',
  'dd MMMM, yyyy h:mm:ss a',
  'dd MMMM, yyyy HH:mm:ss',
  'dd MMMM, yyyy H:mm:ss',
  'dd MMMM, yyyy hh:mm a',
  'dd/MM/yyyy hh:mm:ss a',
  'dd MMMM, yyyy h:mm a',
  'dd/MM/yyyy h:mm:ss a',
  'EEEE, dd MMMM, yyyy',
  'dd MMMM, yyyy HH:mm',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'dd MMMM, yyyy H:mm',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'EEEE، d MMMM، y',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yyyy h:mm a',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'dd/MM/yy h:mm a',
  'dd/MM/yyyy H:mm',
  'dd/MM/yy HH:mm',
  'h:mm:ss a zzzz',
  'dd MMMM, yyyy',
  'dd/MM/yy H:mm',
  'h:mm:ss a z',
  'MMMM, yyyy',
  'd MMMM، y',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'd MMM، y',
  'h:mm:ss a',
  'HH:mm:ss',
  'dd/MM/yy',
  'H:mm:ss',
  'dd MMMM',
  'hh:mm a',
  'd/M/yy',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];