formats["vi-vn"] = [
  '\'Ngày\' dd \'tháng\' MM \'năm\' y',
  'EEEE, \'ngày\' dd MMMM \'năm\' y',
  'dd MMMM yyyy hh:mm:ss a',
  'dd MMMM yyyy h:mm:ss a',
  'dd MMMM yyyy HH:mm:ss',
  'dd-MM-yyyy hh:mm:ss a',
  'dd/MM/yyyy hh:mm:ss a',
  'dd MMMM yyyy H:mm:ss',
  'dd MMMM yyyy hh:mm a',
  'dd-MM-yyyy h:mm:ss a',
  'dd/MM/yyyy h:mm:ss a',
  'dd MMMM yyyy h:mm a',
  'dd-MM-yy hh:mm:ss a',
  'dd-MM-yyyy HH:mm:ss',
  'dd/MM/yy hh:mm:ss a',
  'dd/MM/yyyy HH:mm:ss',
  'dd MMMM yyyy HH:mm',
  'dd-MM-yy h:mm:ss a',
  'dd-MM-yyyy H:mm:ss',
  'dd-MM-yyyy hh:mm a',
  'dd/MM/yy h:mm:ss a',
  'dd/MM/yyyy H:mm:ss',
  'dd/MM/yyyy hh:mm a',
  'dd MMMM yyyy H:mm',
  'dd-MM-yy HH:mm:ss',
  'dd-MM-yyyy h:mm a',
  'dd/MM/yy HH:mm:ss',
  'dd/MM/yyyy h:mm a',
  'dd-MM-yy H:mm:ss',
  'dd-MM-yy hh:mm a',
  'dd-MM-yyyy HH:mm',
  'dd/MM/yy H:mm:ss',
  'dd/MM/yy hh:mm a',
  'dd/MM/yyyy HH:mm',
  'dd-MM-yy h:mm a',
  'dd-MM-yyyy H:mm',
  'dd/MM/yy h:mm a',
  'dd/MM/yyyy H:mm',
  'dd-MM-yy HH:mm',
  'dd/MM/yy HH:mm',
  'HH:mm:ss zzzz',
  'dd-MM-yy H:mm',
  'dd/MM/yy H:mm',
  'dd MMMM yyyy',
  'HH:mm:ss z',
  'dd-MM-yyyy',
  'dd/MM/yyyy',
  'hh:mm:ss a',
  'MMMM yyyy',
  'h:mm:ss a',
  'HH:mm:ss',
  'dd-MM-yy',
  'dd/MM/yy',
  'H:mm:ss',
  'dd MMMM',
  'dd-MM-y',
  'dd/MM/y',
  'hh:mm a',
  'h:mm a',
  'HH:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy-MM-dd hh:mm:ss a',
  'yyyy-MM-dd h:mm:ss a',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd hh:mm a',
  'yyyy-MM-dd h:mm a',
  'yyyy-MM-dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy-MM-dd'
];