formats["zh-cn"] = [
  'EEEE, yyyy\'年\'M\'月\'d\'日\' a hh:mm:ss',
  'EEEE, yyyy\'年\'M\'月\'d\'日\' a h:mm:ss',
  'EEEE, yyyy\'年\'M\'月\'d\'日\' HH:mm:ss',
  'EEEE, yyyy\'年\'M\'月\'d\'日\' H:mm:ss',
  'EEEE, yyyy\'年\'M\'月\'d\'日\' a hh:mm',
  'EEEE, yyyy\'年\'M\'月\'d\'日\' a h:mm',
  'EEEE, yyyy\'年\'M\'月\'d\'日\' HH:mm',
  'EEEE, yyyy\'年\'M\'月\'d\'日\' H:mm',
  'EEEE, yyyy-MM-dd a hh:mm:ss',
  'EEEE, yyyy\'年\'M\'月\'d\'日\'',
  'EEEE, yyyy-MM-dd a h:mm:ss',
  'EEEE, yyyy-MM-dd HH:mm:ss',
  'EEEE, yyyy-MM-dd H:mm:ss',
  'EEEE, yyyy-MM-dd a hh:mm',
  'EEEE, yyyy-MM-dd a h:mm',
  'EEEE, yyyy-MM-dd HH:mm',
  'EEEE, yyyy-MM-dd H:mm',
  'EEEE, yyyy-MM-dd',
  'zzzz ah:mm:ss',
  'M\'月\'d\'日\'',
  'a hh:mm:ss',
  'z ah:mm:ss',
  'a h:mm:ss',
  'HH:mm:ss',
  'ah:mm:ss',
  'H:mm:ss',
  'a hh:mm',
  'a h:mm',
  'HH:mm',
  'ah:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy\'年\'M\'月\'d\'日\' a hh:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' a h:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' HH:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' H:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' a hh:mm',
  'yyyy\'年\'M\'月\'d\'日\' a h:mm',
  'yyyy\'年\'M\'月\'d\'日\' HH:mm',
  'yyyy\'年\'M\'月\'d\'日\' H:mm',
  'yyyy-MM-dd a hh:mm:ss',
  'yyyy.MM.dd a hh:mm:ss',
  'yyyy/MM/dd a hh:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\'',
  'yyyy-MM-dd a h:mm:ss',
  'yyyy.MM.dd a h:mm:ss',
  'yyyy/MM/dd a h:mm:ss',
  'yy/MM/dd a hh:mm:ss',
  'yyyy-M-d a hh:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy.M.d a hh:mm:ss',
  'yyyy.MM.dd HH:mm:ss',
  'yyyy/M/d a hh:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yy/MM/dd a h:mm:ss',
  'yyyy-M-d a h:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd a hh:mm',
  'yyyy.M.d a h:mm:ss',
  'yyyy.MM.dd H:mm:ss',
  'yyyy.MM.dd a hh:mm',
  'yyyy/M/d a h:mm:ss',
  'yyyy/MM/dd H:mm:ss',
  'yyyy/MM/dd a hh:mm',
  'yy-M-d a hh:mm:ss',
  'yy.M.d a hh:mm:ss',
  'yy/M/d a hh:mm:ss',
  'yy/MM/dd HH:mm:ss',
  'yyyy-M-d HH:mm:ss',
  'yyyy-MM-dd a h:mm',
  'yyyy.M.d HH:mm:ss',
  'yyyy.MM.dd a h:mm',
  'yyyy/M/d HH:mm:ss',
  'yyyy/MM/dd a h:mm',
  'yy-M-d a h:mm:ss',
  'yy.M.d a h:mm:ss',
  'yy/M/d a h:mm:ss',
  'yy/MM/dd H:mm:ss',
  'yy/MM/dd a hh:mm',
  'yyyy-M-d H:mm:ss',
  'yyyy-M-d a hh:mm',
  'yyyy-MM-dd HH:mm',
  'yyyy.M.d H:mm:ss',
  'yyyy.M.d a hh:mm',
  'yyyy.MM.dd HH:mm',
  'yyyy/M/d H:mm:ss',
  'yyyy/M/d a hh:mm',
  'yyyy/MM/dd HH:mm',
  'y年M月d日EEEE',
  'yy-M-d HH:mm:ss',
  'yy.M.d HH:mm:ss',
  'yy/M/d HH:mm:ss',
  'yy/MM/dd a h:mm',
  'yyyy-M-d a h:mm',
  'yyyy-MM-dd H:mm',
  'yyyy.M.d a h:mm',
  'yyyy.MM.dd H:mm',
  'yyyy/M/d a h:mm',
  'yyyy/MM/dd H:mm',
  'yyyy\'年\'M\'月\'',
  'yy-M-d H:mm:ss',
  'yy-M-d a hh:mm',
  'yy.M.d H:mm:ss',
  'yy.M.d a hh:mm',
  'yy/M/d H:mm:ss',
  'yy/M/d a hh:mm',
  'yy/MM/dd HH:mm',
  'yyyy-M-d HH:mm',
  'yyyy.M.d HH:mm',
  'yyyy/M/d HH:mm',
  'yy-M-d a h:mm',
  'yy.M.d a h:mm',
  'yy/M/d a h:mm',
  'yy/MM/dd H:mm',
  'yyyy-M-d H:mm',
  'yyyy.M.d H:mm',
  'yyyy/M/d H:mm',
  'yy-M-d HH:mm',
  'yy.M.d HH:mm',
  'yy/M/d HH:mm',
  'y年M月d日',
  'yy-M-d H:mm',
  'yy.M.d H:mm',
  'yy/M/d H:mm',
  'yyyy-MM-dd',
  'yyyy.MM.dd',
  'yyyy/MM/dd',
  'yy/MM/dd',
  'yyyy-M-d',
  'yyyy.M.d',
  'yyyy/M/d',
  'yy-M-d',
  'yy.M.d',
  'yy/M/d',
  'yyyy.M'
];