formats["zh-hk"] = [
  'EEEE, d MMMM, yyyy HH:mm:ss',
  'EEEE, d MMMM, yyyy H:mm:ss',
  'EEEE yyyy MM dd HH:mm:ss',
  'EEEE, d MMMM, yyyy HH:mm',
  'EEEE yyyy MM dd H:mm:ss',
  'EEEE, d MMMM, yyyy H:mm',
  'EEEE yyyy MM dd HH:mm',
  'd MMMM, yyyy HH:mm:ss',
  'EEEE yyyy MM dd H:mm',
  'd MMMM, yyyy H:mm:ss',
  'EEEE, d MMMM, yyyy',
  'd MMMM, yyyy HH:mm',
  'd MMMM, yyyy H:mm',
  'd/M/yyyy HH:mm:ss',
  'dd/MM/yy HH:mm:ss',
  'd/M/yyyy H:mm:ss',
  'dd/MM/yy H:mm:ss',
  'EEEE yyyy MM dd',
  'ah:mm:ss [zzzz]',
  'd/M/yy HH:mm:ss',
  'd/M/yy H:mm:ss',
  'd/M/yyyy HH:mm',
  'dd/MM/yy HH:mm',
  'd/M/yyyy H:mm',
  'dd/MM/yy H:mm',
  'ah:mm:ss [z]',
  'd MMMM, yyyy',
  'd/M/yy HH:mm',
  'd/M/yy H:mm',
  'MMMM, yyyy',
  'HH:mm:ss',
  'ah:mm:ss',
  'd/M/yyyy',
  'dd/MM/yy',
  'H:mm:ss',
  'd MMMM',
  'd/M/yy',
  'HH:mm',
  'ah:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy MM dd HH:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yyyy MM dd H:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy/MM/dd H:mm:ss',
  'yy/MM/dd HH:mm:ss',
  'yyyy/M/d HH:mm:ss',
  'yy/MM/dd H:mm:ss',
  'yyyy MM dd HH:mm',
  'yyyy-MM-dd HH:mm',
  'yyyy/M/d H:mm:ss',
  'yyyy/MM/dd HH:mm',
  'y年M月d日EEEE',
  'yy/M/d HH:mm:ss',
  'yyyy MM dd H:mm',
  'yyyy-MM-dd H:mm',
  'yyyy/MM/dd H:mm',
  'yy/M/d H:mm:ss',
  'yy/MM/dd HH:mm',
  'yyyy/M/d HH:mm',
  'yy/MM/dd H:mm',
  'yyyy/M/d H:mm',
  'yy/M/d HH:mm',
  'y年M月d日',
  'yy/M/d H:mm',
  'yyyy MM dd',
  'yyyy-MM-dd',
  'yyyy/MM/dd',
  'yy/MM/dd',
  'yyyy/M/d',
  'yy/M/d'
];