formats["zh-tw"] = [
  'ah:mm:ss [zzzz]',
  'M\'月\'d\'日\'',
  'ah:mm:ss [z]',
  'a hh:mm:ss',
  'a h:mm:ss',
  'HH:mm:ss',
  'ah:mm:ss',
  'H:mm:ss',
  'a hh:mm',
  'a h:mm',
  'HH:mm',
  'ah:mm',
  'H:mm',
  'yyyy\'-\'MM\'-\'dd\'T\'HH\':\'mm\':\'ss',
  'yyyy\'年\'MM\'月\'dd\'日\' a hh:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' a h:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' HH:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' a hh:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' H:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' a hh:mm',
  'yyyy\'年\'M\'月\'d\'日\' a h:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' a h:mm',
  'yyyy\'年\'M\'月\'d\'日\' HH:mm:ss',
  'yyyy\'年\'MM\'月\'dd\'日\' HH:mm',
  'yyyy\'年\'M\'月\'d\'日\' H:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\' a hh:mm',
  'yyyy\'年\'MM\'月\'dd\'日\' H:mm',
  'yyyy\'年\'M\'月\'d\'日\' a h:mm',
  'yyyy\'年\'M\'月\'d\'日\' HH:mm',
  'yyyy\'年\'M\'月\'d\'日\' H:mm',
  'yyyy\'年\'MM\'月\'dd\'日\'',
  'yyyy-MM-dd a hh:mm:ss',
  'yyyy/MM/dd a hh:mm:ss',
  'yyyy\'年\'M\'月\'d\'日\'',
  'yyyy-MM-dd a h:mm:ss',
  'yyyy/MM/dd a h:mm:ss',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy/M/d a hh:mm:ss',
  'yyyy/MM/dd HH:mm:ss',
  'yyyy-MM-dd H:mm:ss',
  'yyyy-MM-dd a hh:mm',
  'yyyy/M/d a h:mm:ss',
  'yyyy/MM/dd H:mm:ss',
  'yyyy/MM/dd a hh:mm',
  'yyyy-MM-dd a h:mm',
  'yyyy/M/d HH:mm:ss',
  'yyyy/MM/dd a h:mm',
  'y年M月d日 EEEE',
  'yyyy-MM-dd HH:mm',
  'yyyy/M/d H:mm:ss',
  'yyyy/M/d a hh:mm',
  'yyyy/MM/dd HH:mm',
  'yyyy-MM-dd H:mm',
  'yyyy/M/d a h:mm',
  'yyyy/MM/dd H:mm',
  'yyyy\'年\'M\'月\'',
  'yyyy/M/d HH:mm',
  'yyyy/M/d H:mm',
  'y年M月d日',
  'yyyy-MM-dd',
  'yyyy/MM/dd',
  'yyyy/M/d',
  'y/M/d'
];